- External/Plugins/AS2Context/Context.cs
- External/Plugins/CodeRefactor/Commands/FindAllReferences.cs
- External/Plugins/CodeRefactor/Commands/Move.cs
- External/Plugins/CodeRefactor/Commands/Rename.cs
- External/Plugins/CodeRefactor/Commands/RenameFile.cs
- External/Plugins/CodeRefactor/PluginMain.cs
- External/Plugins/CodeRefactor/Provider/DocumentHelper.cs
- External/Plugins/CodeRefactor/Provider/RefactoringHelper.cs
- External/Plugins/ProjectManager/Actions/FileActions.cs
- External/Plugins/ProjectManager/Projects/Haxe/HaxeProject.cs
- PluginCore/PluginCore/Helpers/FileHelper.cs
- PluginCore/PluginCore/Managers/DocumentManager.cs
- PluginCore/PluginCore/Resources/de_DE.resX
- PluginCore/PluginCore/Resources/en_US.resX
- PluginCore/PluginCore/Resources/eu_ES.resX
- PluginCore/PluginCore/Resources/ja_JP.resX
- PluginCore/PluginCore/Resources/zh_CN.resx
Fixed tons of errors and unsupported cases, mainly in the Move command. Should fix issues #144 #162 #187 #400 #518 and several more issues not reported.
Rename command left modified files unsaved, while Move command saved them, the latter is the common approach taken, and I'd say seeing tons of files with unsaved changes may confuse the user, so made Rename to behave the same.
The Move command tried to keep modified files open, but the code was wrong, I fixed the initial check but left it commented, I think it pollutes the user interfaces when the refactoring affects many files. If this feature is wanted it would require some further changes.
When the Move and Rename commands finish, the affected files that were initially open are kept open, although the position is lost.
Removed calls to …
> Project tree refactoring fixes

- External/Plugins/ProjectManager/Actions/FileActions.cs
The old MoveDirectory method had watcher calls, but Move, the only function that was calling it, is already wrapped in watcher calls.
EDIT: BTW, I'll commit more improvements to the Move and Rename commands during this week.
> Recovered watcher disable/enable calls

- External/Plugins/ASCompletion/Model/FileModel.cs
Wouldn't have committed this to the development branch if it were not because it fixes some possible nasty crashes, and FD 4.7 is not released yet.
EDIT: For example the ones fixed here: https://github.com/apache/flex-flexunit/commit/1cf55d524f47affdb0c4e0e60d511d39e3d6e8b2
BTW, I was the one to add this crash while fixing other wrong cases and add some unsupported ones.
> Fix for crash in some incorrectly defined metadata tags

- External/Plugins/ProjectManager/Controls/PropertiesDialog.cs
- External/Plugins/ProjectManager/Projects/Haxe/HaxeProjectReader.cs
- FlashDevelop/Bin/Debug/Settings/Platforms/Haxe/flambe.xml
- FlashDevelop/Bin/Debug/Settings/Platforms/Haxe/lime.xml
- FlashDevelop/Bin/Debug/Settings/Platforms/Haxe/nme.xml
- PluginCore/PluginCore/PlatformData.cs
- PluginCore/PluginCore/Resources/de_DE.resX
- PluginCore/PluginCore/Resources/en_US.resX
- PluginCore/PluginCore/Resources/eu_ES.resX
- PluginCore/PluginCore/Resources/ja_JP.resX
- PluginCore/PluginCore/Resources/zh_CN.resx
Little refactor of PropertiesDialog and made the Compiler Options grid read only for OpenFL/etc. projects
> Read only project properties

- External/Plugins/ASCompletion/CustomControls/StateSavingTreeView.cs
- External/Plugins/ASCompletion/Win32/FixedTreeView.cs
With latest modifications treeview flickering was solved for some operations, with these ones the treeview drawing is locked while removing and adding new nodes (BeginUpdate() and EndUpdate() isn't 100% working for TreeView).
On all the machines I've tested I now see 0 flickering. The only case where the user may think there is flickering is when writing incomplete code before other functions as they'll be lost, and once the parse is able to get again the following functions they'll reappear.
I don't see the need of Begin/EndUpdate in PluginUI.HighlightAllMachingDeclaration and highlightTimer_Tick, I tried removing the calls, and did not notice any flickering, but left them just in case...
> Lock redrawing completely 

- External/Plugins/CodeRefactor/Commands/Move.cs
NOTE: This exposes some other limitations, eg: highlighting is wrong on some cases where the import is inserted. I'm aware, it will be handled on the upcoming rewrite of the class. More important generating code that compiles, than these other problems.
> Ensure inserting import on Move is always added to a correct location

- External/Plugins/CodeRefactor/Commands/Move.cs
> Refactor->Move: fix for moving Haxe modules that don't specify a package

- External/Plugins/ASCompletion/CustomControls/ModelsExplorer.Designer.cs
- External/Plugins/ASCompletion/CustomControls/ModelsExplorer.cs
Use FixedTreeView instead of normal TreeView. It solves the flickering seen sometimes.
Capture the Escape key to close the panel as originally intended.
> Type Explorer improvements

- External/Plugins/HaXeContext/Completion/HaxeComplete.cs
This doesn't provide overload completion but at least prevents overloaded functions to appear multiple times in completion list.
Adresses https://github.com/HaxeFoundation/haxe/issues/560
> Prevent overloads to show up

- External/Plugins/FlashDebugger/Helpers/MenusHelper.cs
It could throw a NPE in some exceptional cases when the debugger is stopped.
> Fixed isDebuggerSuspended check

- External/Plugins/AS3Context/AbcConverter.cs
Fixes #606 : force extract const values provided in fat SWCs even if no doc is specified.
> SWC const value extraction fix

- External/Plugins/ASCompletion/Completion/ASComplete.cs
- External/Plugins/ASCompletion/Completion/ASGenerator.cs
- FlashDevelop/MainForm.cs
- PluginCore/ScintillaNet/ScintillaControl.cs
Previous returned only \r. This also matches other line related methods. Push here fixes-
> GetLine is now fixed to match Scintilla and return all EOLs, we need to fix and review all usage

- appman.xml
TrackOpenFile extension is no longer needed now that ProjectManager has the Track Active File option.
> Update appman.xml to remove TrackOpenFile.

- PluginCore/DockPanelSuite/Docking/Measures.cs
Splitters were not being scaled with DPI so the target area was very thin.
> Scale the SplitterSize for DockPanels

- FlashDevelop/Bin/Debug/Settings/MainMenu.xml
- FlashDevelop/Bin/Debug/Settings/ScintillaMenu.xml
- PluginCore/ScintillaNet/ScintillaControl.cs
Like FD, IntelliJ IDEA also has a Ctrl+D shortcut to duplicate the current selection (or line if the selection is empty), but it also
- moves the caret down one line if a line is duplicated
- moves the selection to the duplicated text if the selection is duplicated
I think this is convenient, so I implemented the same behavior here.
It does seem a little counter-intuitive when you undo the duplication, because the selection doesn't go back to what it was before. I tried `Begin` / `EndUndoAction()`, but Scintilla doesn't care about selection changes in the undo history.
The [docs](http://www.scintilla.org/ScintillaDoc.html) say:
>Scintilla saves actions that change the document. Scintilla does not save caret and selection movements, view scrolling and the like.
I'm not sure how this …
> Move the caret / selection in SelectionDuplicate

- External/Themes/FullThemes/DefaultTheme/$(BaseDir)/Settings/Themes/Default.fdi
- External/Themes/FullThemes/DimGrayTheme/$(BaseDir)/Settings/Themes/DimGray.fdi
- External/Themes/FullThemes/ObsidianTheme/$(BaseDir)/Settings/Themes/Obsidian.fdi
- External/Themes/FullThemes/ThyleusTheme/$(BaseDir)/Settings/Themes/Thyleus.fdi
- FlashDevelop/Bin/Debug/Settings/Themes/Default.fdi
- FlashDevelop/Bin/Debug/Settings/Themes/DimGray.fdi
- FlashDevelop/Bin/Debug/Settings/Themes/Obsidian.fdi
- FlashDevelop/Bin/Debug/Settings/Themes/Thyleus.fdi
- PluginCore/DockPanelSuite/Customization/DockPanelStripRenderer.cs
- PluginCore/DockPanelSuite/Customization/VS2005DockPaneCaption.cs
- PluginCore/DockPanelSuite/Customization/VS2005DockPaneStrip.cs
Added more settings for differentiating between Active and Inactive tabs. Also, updated the included themes.
StatusStrip.ForeColor is respected
Added VS2005DockPaneCaption.ActiveForeColor
Added VS2005DockPaneCaption.ImageColor
Added VS2005DockPaneCaption.ActiveImageColor
Added VS2005DockPaneStrip.ToolActiveBorderColor
Added VS2005DockPaneStrip.ToolActiveForeColor
Added VS2005DockPaneStrip.DocTabActiveForeColor
Added VS2005DockPaneStrip.ImageColor
Put it all together and it makes for some nice themes.
> Add more themeing

- External/Plugins/HaXeContext/Context.cs
This makes sure version changes of haxelibs are detected.
See #649.
> Update the HaxeProject when the user refreshes the project

- PluginCore/PluginCore/Resources/de_DE.resX
- PluginCore/PluginCore/Resources/en_US.resX
- PluginCore/PluginCore/Resources/eu_ES.resX
- PluginCore/PluginCore/Resources/ja_JP.resX
- PluginCore/PluginCore/Resources/zh_CN.resx
The description wouldn't show up / produce an error in the output panel.
> Fix localization name of HighlightMatchingWordsDelay

- External/Plugins/ProjectManager/Projects/ProjectPaths.cs
- Optimize GetRelativePath for trivial cases (very intensive usage in PM tree)
- Do not consider path sharing the same drive letter as relative (ie. on C:\ common) - should fix #655
> Project GetRelativePath improvement

- External/Plugins/CodeRefactor/Commands/FindAllReferences.cs
- External/Plugins/CodeRefactor/Commands/Move.cs
- External/Plugins/CodeRefactor/Commands/Rename.cs
- External/Plugins/CodeRefactor/Provider/DocumentHelper.cs
- External/Plugins/CodeRefactor/Provider/RefactoringHelper.cs
- External/Plugins/FlashDebugger/Helpers/ScintillaHelper.cs
- FlashDevelop/Dialogs/FRInFilesDialog.cs
Instead use the returned ITabbedDocument.
Under some rare circumstances (I guess only on some multithreading scenarios?) the MainForm.CurrentDocument was not immediately updated to reflect the newly opened document. When this happened it caused the refactoring commands to lose some of the changes made to files, finding references to lose some results, the debugger to not open files when expected on errors or breakpoints...
> Changed most uses of MainForm.OpenEditableDocument

- External/Plugins/ASCompletion/Model/PathModel.cs
Got a `FileNotFoundException` here - the `Directory.getFiles()` call was surround by a try..catch, the `GetDirectories()` call later wasn't.
> PathModel::ExploreFolder: fix potential FileNotFoundException

- External/Plugins/ASCompletion/Completion/ASComplete.cs
- External/Plugins/ASCompletion/Model/ASFileParser.cs
- External/Plugins/ASCompletion/PluginMain.cs
Do not skip \ and the next character when parsing strings. All IDEs I've tried leave them in hints, and when there are escaped Unicode or ASCII characters it results in strange output. Also, skipping it could result in other wrong results, for example some bad formed include statement.
ASComplete.FindNearSymbolInFunctDef has been rewritten to better detect parameters. The new function is larger, but is faster, more inline with file parsing, and I find it to be easier to get what the function actually does than the previous one, but the latter may be just something subjective. Are ({[ really possible? I left them, but sincerely, I don't know when they can appear (aside from trying to use objects and arrays in default values, which is wrong).
This adds multi line string support in Haxe in …
> Better string parsing. Fixes Issue #444

- External/Plugins/ASCompletion/Model/ASFileParser.cs
- External/Plugins/BookmarkPanel/PluginUI.cs
- External/Plugins/CodeRefactor/Commands/Move.cs
- External/Plugins/CodeRefactor/Commands/OrganizeImports.cs
- FlashDevelop/Controls/QuickFind.cs
- FlashDevelop/Dialogs/FRInDocDialog.cs
- PluginCore/PluginCore/FRService/FRRunner.cs
- PluginCore/PluginCore/FRService/FRSearch.cs
- PluginCore/ScintillaNet/ScintillaControl.cs
- Parse Haxe regex literals correctly.
- Take into account regex literals can follow an object literal property.
- Take into account regexes in FRSearch.
It could cause some (minor) completion issues but more importantly, it's responsible for this:
https://twitter.com/_bigp/status/594314905878134786
EDIT: Surely regex parsing should take into account the possible flags as well.
> Improved regex handling.

- External/Plugins/ASCompletion/Completion/ASComplete.cs
- Top-level getters were not supported.
- fix in EvalTail with top-level expressions resolution
> Fixes: Top level Class autocompletion stopped working #692

- PluginCore/PluginCore/Utilities/PathWalker.cs
When extension mask is 3 chars (ie. not .as or .hx, but .hxp) it will match any extension of more characters (ie. .hxproj).
The fix adds a verification that the matched file extension really matches the mask.
> Fixes: Find And Replace In Files *.hxp extension filter includes .hproj #694

- PluginCore/PluginCore/Controls/Common.cs
BreakPointUI grid was still rendering cells with the default background color. These changes update the DefaultCellStyle when themes are applied.
> Apply Theme to DataGridView cells

- External/Plugins/AirProperties/PluginMain.cs
- External/Plugins/ProjectManager/Controls/Icons.cs
- External/Plugins/ProjectManager/Controls/TreeBar.cs
- External/Plugins/ProjectManager/PluginMain.cs
Not 100% sure how this should behave when "track active document" is enabled. Currently it just collapses all nodes except root / project nodes and track active document is applied again when switching documents.
It might seem weird if clicking the "collapse all" button doesn't close the source node, which would be the case if track active document was applied after collapse all.
> Project Manager: add a "collapse all" button, closes #721

- External/Plugins/ASCompletion/Model/ASFileParser.cs
Not sure if this is the best solution (maybe `.dump` / non-`.hx` files should not be parsed in the first place?), but at least it gets rid of the exception for now.
> ASFileParser#FinalizeModel(): check for invalid file name chars, closes #715

- External/Plugins/ProjectManager/Controls/TreeView/OtherNodes.cs
Doesn't solve the original issue from #704 but at least the order of haxelibs is alphabetical now:
(compared to)
> ProjectManager: apply some sorting to references, #704

- FlashDevelop/Docking/TabbedDocument.cs
When editing in split mode the splitter size was not being scaled based on DPI.
> Scale the Splitter size based on DPI

- External/Plugins/FlashDebugger/Helpers/ScintillaHelper.cs
- FlashDevelop/Managers/ScintillaManager.cs
- PluginCore/PluginCore.csproj
- PluginCore/ScintillaNet/RGBA.cs
- PluginCore/ScintillaNet/ScintillaControl.cs
Since RGBA supports an alpha channel marker images look better when scaled for high dpi.
- Added MarkerDefineRGBAImage method.
- Added RGBA static class for converting a Bitmap into a byte[].
- Updated the breakpoint, current line, and bookmark markers to use
DefineRGBA method.
> Changed scintilla marker images from using XPM to RGBA.

- External/Plugins/ProjectManager/Controls/TreeView/ProjectTreeView.cs
Resolves #738.
- ProjectTreeView handles ApplyTheme event.
- On ApplyTheme all nodes are updated with the new ForeColor and BackColor.
> ProjectTreeView refreshes colors on ApplyTheme

- External/Plugins/ASCompletion/Completion/ASComplete.cs
- External/Plugins/HaXeContext/Context.cs
Checking for `CurrentMember == null` was broken (see #765) and isn't a good approach to begin with, since metadata can be used inside of functions as well (`@:mergeBlock` for example).
> Metadata completion fixes, closes #765

- FlashDevelop/MainForm.cs
This is very convenient in XML and HTML files (which have no line comments in the traditional sense) - instead of having to select the line and do a block comment, line comment simply does a block comment on the current line.
> Line Comment: use block comment on the current line if not available

- External/Plugins/ASClassWizard/Controls/TreeView/SimpleDirectoryNode.cs
- External/Plugins/ASClassWizard/PluginMain.cs
- External/Plugins/ASClassWizard/Resources/ASClassOptions.cs
- External/Plugins/ASClassWizard/Wizards/AS3ClassWizard.cs
- External/Plugins/ASClassWizard/Wizards/ClassBrowser.cs
- External/Plugins/ASClassWizard/Wizards/GListBox.cs
- External/Plugins/ASClassWizard/Wizards/PackageBrowser.cs
- External/Plugins/ASCompletion/Model/MemberModel.cs
Includes a bit of code cleanup, the relevant part is the diff from the second commit: https://github.com/fdorg/flashdevelop/commit/68a4bc8260b76402fc62f0818c87bdbc9c4d5ffd
> ClassBrowser: fix imported types being included, closes #775

- External/Plugins/ProjectManager/Controls/Icons.cs
- FlashDevelop/Bin/Debug/Settings/TabMenu.xml
The icons used in the TabMenu and the PM context menu were inconcistent with the one in the main menu.
> Use the same Explorer icon everywhere

- External/Plugins/ASCompletion/Completion/ASComplete.cs
- PluginCore/PluginCore/Controls/CompletionList.cs
Having to type the `;` manually every time when you already selected the item from the completion list is somewhat tedious.
> Automatically add the semicolon after imports

- External/Plugins/ASClassWizard/PluginMain.cs
- External/Plugins/ASCompletion/Completion/ASGenerator.cs
- External/Plugins/ASCompletion/Completion/TemplateUtils.cs
Fixes #801: Bug: [Haxe] - Overriding method with optional parameters generates incorrect super() call
> Do not generate super calls with Haxe's '?' marker (optional parameter).

- External/Plugins/ASCompletion/Context/ASContext.cs
the model's path is "refreshed" every time it is resolved to be used for the current document.
> Fixes issue #799 with FileModels path casing

- External/Tools/FDBuild/Building/AS3/MxmlcArgumentBuilder.cs
https://blogs.apache.org/flex/entry/apache_flex_announces_the_release
> Support of tag -advanced-telemetry for apache flex sdk 4.10.0 and newer.

- External/Plugins/AS3Context/Compiler/FlexShells.cs
Now `@mxmlc` can receive `+configname=air` argument. And paths can be quoted with `"`.
> quickbuild bug fix

- External/Plugins/ASCompletion/Completion/ASDocumentation.cs
Use the RichToolTip.ForeColor if it is set by the UI theme.
> Update ASDocumentation.GetShortcutDocs to use theme color if set

- External/Plugins/ProjectManager/Controls/FDMenus.cs
- External/Plugins/ProjectManager/PluginMain.cs
Sometimes the TargetBuild combo loses its value when building - an empty element sometimes gets inserted in the recent targetbuilds list also.
> Prevent occasional loss of target build value when building

- FlashDevelop/Controls/QuickFind.cs
Improves the appearance of the QuickFind control when using a dark theme.
Adding ComboBox.ForeColor to the ui theme completes the look.
> Update QuickFind to fallback on the DockPanelStripRenderer

- External/Plugins/AS2Context/Context.cs
- External/Plugins/AS3Context/Context.cs
- External/Plugins/ASCompletion/Completion/ASComplete.cs
- External/Plugins/ASCompletion/Completion/ASGenerator.cs
- External/Plugins/ASCompletion/Completion/ContextFeatures.cs
- External/Plugins/ASCompletion/PluginMain.cs
- External/Plugins/CodeRefactor/CodeRefactor.csproj
- External/Plugins/CodeRefactor/Commands/RefactorCommand.cs
- External/Plugins/CodeRefactor/PluginMain.cs
- External/Plugins/CodeRefactor/RefactorItem.cs
- External/Plugins/HaXeContext/Context.cs
- External/Plugins/LoomContext/Context.cs
- PluginCore/PluginCore/Controls/CompletionList.cs
I had a feeling that the Refactor menus are very useful, but they are not easily accessible due to the fact that every option needs a separate shortcut assigned in order to access using keyboard only (unless you press the right-click button on your keyboard which is cheating). So, inspired by Visual Studio, I thought it would be nice if the available options were to show up in the existing code generator menu (assign the shortcut to `Ctrl+OemPeriod` and boom). 
Currently
- Rename
- Extract Method
- Extract Local Variable
- Generate Delegate Methods
- Organise Imports
- Truncate Imports
are available in the completion list, but more can be added with just 2 lines of code for each. (Edit: 1 line of code after 54bdb08)
Plus, extended the support of `Convert to Constant` to also work for …
> Include available Refactor menus in Contextual Code Generation list

- External/Plugins/ProjectManager/PluginMain.cs
- Try to resync on project opening.
- If the node for the file is not found, try to find it in the future. This can happen with files created through wizards. I don't think this has any negative impact on files outside of the project, the check is quite simple and only happens on file changes.
This should fix issue #928
> Track active document fixes.

- External/Plugins/ASCompletion/Completion/ASComplete.cs
When displaying classes check for type parameters and display them if existing.
When autocompleting after : check in functions for the existance of type parameters. Previously this case was breaking completion completely.
The first screenshot also shows this fix, before the completion list wouldn't be shown in there unless forced with Ctrl+Alt+Space.
> Haxe type parameters improvements

- External/Plugins/AS3Context/PluginMain.cs
- External/Plugins/ProjectManager/Helpers/LineEntryDialog.cs
- External/Plugins/ProjectManager/PluginMain.cs
- FlashDevelop/Dialogs/ShortcutDialog.cs
- FlashDevelop/MainForm.cs
- FlashDevelop/Managers/ShortcutManager.cs
- PluginCore/PluginCore/Interfaces.cs
Small changes. Currently 2 changes are made.
**1.**
`ShortcutManager.RegisteredItems` is changed to the type `Dictionary<string, ShortcutItem>` for better performance of searching by ID. In relation to this change, 
```C#
string IMainForm.GetShortcutItemId(Keys)
Dictionary<Keys, string> IMainForm.GetShortcutItemsByKeys()
```
have been added. With those changes, codes like below
```C#
if (keys == PluginBase.MainForm.GetShortcutItemKeys("Namespace.Shortcut1") { }
else if (keys == PluginBase.MainForm.GetShortcutItemKeys("Namespace.Shortcut2") { }
else if (keys == ...
```
which had to loop through the whole shortcut list _n_ number of times previously, can be replaced with either
```C#
switch (PluginBase.MainForm.GetShortcutItemId(keys))
{
case "Namespace.Shortcut1": { } break;
case …
```
> Updates to MainForm (plus Related Things)

- External/Plugins/ProjectManager/Projects/BuildEventVars.cs
Fixed the bug of `BaseDir` currently returning `string.Empty` when executed from fdbuild.exe.
> BuildEventVars

- FlashDevelop/Dialogs/ShortcutDialog.cs
The dialog waits for a certain delay when the filter is updated, before re-populating the list.
This prevents the lag caused on slow computers (mine) when typing fast enough.
> Delayed Update for ShortcutDialog

- PluginCore/PluginCore/Interfaces.cs
When projects other than `FlashDevelop` accesses the main form, they get the type of the interface `IMainForm` instead of `MainForm`. So they don't get to see any documentation on the properties and methods.
Copy & pasterino-ed all documentation from `MainForm` to `IMainForm`.
> IMainForm Documentation

- External/Plugins/AS3Context/Context.cs
- FlashDevelop/Bin/Debug/Library/AS3/intrinsic/FP11/Vector.as
- FlashDevelop/Bin/Debug/Library/AS3/intrinsic/FP19/Vector.as
Related to the PR #986.
Intrinsic library paths are now added from the highest version number downwards.
PR #986 modified `Vector.as` in the folder `FP11` but it still does not work since there is a same intrinsic class defined in `FP10` folder. It seems that first registered is being used, so the solution is to register from the highest version number of FP.
Added `FP19\Vector.as` as well.
> AS3 Intrinsic Library Improvement

- External/Plugins/ASCompletion/Completion/ASComplete.cs
When pressing Enter on a closing brace `}`, move it to its own line and fix indentation.
Eg.
```javascript
var foo = {|};
var foo = {
|
}
```
Note: fixing a bad code change that tended to delete the closing brace because it was based on closing brace automatic insertion, which, by design, could NOT insert a closing brace, resulting in a confusing missing brace.
> Fix auto indent of closing brace

- External/Plugins/ASCompletion/ASCompletion.csproj
- External/Plugins/ASCompletion/Completion/ASComplete.cs
- External/Plugins/ASCompletion/Completion/CodeUtils.cs
(eg. `classList` isn't a `class` declaration)
Fixes issue #960
> When looking up keywords, verify they have spaces around

- External/Plugins/ASCompletion/Completion/ASComplete.cs
- in the imports section, the import (eg. `flash.geom.*` disappears and is reinserted in a weird location, while the `import` keyword stays,
- in a function body, nothing happens.
This seem to be a bad regression - the intention was likely that you can type `flash.geom.*` anywhere in your code to generate the corresponding import.
Reported: http://www.flashdevelop.org/community/viewtopic.php?p=54821#p54821
Note: candidate for unit tests
> Fixes typing a wildcard import 

- FlashDevelop/Dialogs/ShortcutDialog.cs
- FlashDevelop/MainForm.cs
- PluginCore/PluginCore/Resources/de_DE.resX
- PluginCore/PluginCore/Resources/en_US.resX
- PluginCore/PluginCore/Resources/eu_ES.resX
- PluginCore/PluginCore/Resources/ja_JP.resX
- PluginCore/PluginCore/Resources/zh_CN.resx
As @Neverbirth suggested, closes #784.
The change fixes numerous bugs caused from the previous structure, and also adds new features:
* All conflicts are highlighted in `Color.DarkRed`.
* View custom shortcuts without moving your mouse to click the check box. Start the filter with the key `"*"`.
* View all conflicts with the filter starting keyword `"?"`.
* Have options filter keywords combined in any order.
* The dialog is now very very grumpy that it won't close until you resolve all conflicts. 
* All changes are only applied when the dialog closes.
> ShortcutDialog improvements.

- .gitignore
The new unit test project from #1012 installs NuGet packages which leads to untracked files.
> Add packages/ to .gitignore

- PluginCore/ScintillaNet/ScintillaControl.cs
It seems to be related to how latest Scintilla in the repo has been compiled. Check here about this problem:
https://www.autoitscript.com/forum/topic/166711-compile-scilexer-library-x32x64-visual-studio-2010-2012-2013/
This PR fixes this case, but from reading around and checking latest ScintillaNet libraries, I'd say Scintilla should be recompiled.
> Fixed Scintilla loading

- FlashDevelop/Dialogs/ShortcutDialog.cs
- PluginCore/PluginCore/Resources/de_DE.resX
- PluginCore/PluginCore/Resources/en_US.resX
- PluginCore/PluginCore/Resources/eu_ES.resX
- PluginCore/PluginCore/Resources/ja_JP.resX
- PluginCore/PluginCore/Resources/ko_KR.resX
- PluginCore/PluginCore/Resources/zh_CN.resx
- Reordered controls inside ShortcutDialog.
- Removed hardcoded strings as they will be overridden by localisation.
- Use FindImage16() for the images.
- Open, Save As -> Import, Export
- Use string.StartsWith(char) extension method.
- Conflicts warning does not show on dialog load.
- Revert All To Default does not trigger conflicts warning to show up (althought imho there should be no conflicts among the default shortcuts).
- Conflicts warning shows up after the listview is updated when custom shortcuts are imported.
- Added a tip to the search label.
> Shortcut dialog

- FlashDevelop/Dialogs/ShortcutDialog.cs
ContextMenu icons shouldn't change color according to the theme.
Now that there are no conflicts by default, suppressing warning message when reverting all to default is not needed.
> ShortcutDialog minor cleanup

- External/Plugins/HaXeContext/Completion/HaxeComplete.cs
If the position service returns an error positionResults is not initialized and later throws an error, and since the error is in a thread, FlashDevelop completely crashes.
> Fix NRE if the position service returns an error.

- External/Plugins/AS3Context/AbcConverter.cs
- External/Plugins/AS3Context/MxmlComplete.cs
- External/Plugins/ASCompletion/Completion/ASComplete.cs
- External/Plugins/ASCompletion/Model/ASFileParser.cs
- External/Plugins/ASCompletion/Model/ClassModel.cs
This is more correct as metadata is part of the class, not the file, and you may have multiple classes with independent metadatas, before this wouldn't work at all.
For the sake of completeness, added "Default" metadata parsing from SWC files.
> Add metadata to the current class, not the file model.

- External/Plugins/ASCompletion/Model/ASFileParser.cs
- Tests/External/Plugins/ASCompletion.Tests/ASCompletion.Tests.csproj
- Tests/External/Plugins/ASCompletion.Tests/Model/ASFileParserTests.cs
- Tests/External/Plugins/ASCompletion.Tests/Test Files/parser/haxe/MethodAfterGenericReturnTest.hx
Fixes #1075. This only happened if the following member was missing any accessor, and could also happen with anonymous types under the same conditions.
> Parsing fix

- External/Plugins/ASCompletion/Model/ASFileParser.cs
- Tests/External/Plugins/ASCompletion.Tests/ASCompletion.Tests.csproj
- Tests/External/Plugins/ASCompletion.Tests/Model/ASFileParserTests.cs
- Tests/External/Plugins/ASCompletion.Tests/Test Files/parser/haxe/WrongSyntaxCompilerMetaAfterMethodWithNoType.hx
- Tests/External/Plugins/ASCompletion.Tests/Test Files/parser/haxe/WrongSyntaxCompilerMetaAfterVarWithNoType.hx
This fixes methods setting some compiler metadata as its type if the meta has arguments and they are not fully written yet.
Fixes issue #372 (last Gama11's comment). EDIT: Fixed only after a function with no type. If it's a var it's not working right yet.
> Clear current member at the final } if it's a method

- FlashDevelop/Dialogs/SettingDialog.cs
If the typical use case is anything like mine, this saves a lot of mouse clicks.
> SettingsDialog: focus the filter text when showing the dialog

- External/Plugins/CodeRefactor/Controls/MoveDialog.cs
Аdds the ability to use a package name syntax to quickly select the path where the class will be moved.
> [CodeRefactor MoveDialog] Аdds the ability to use a package name syntax.

- External/Plugins/ResultsPanel/PluginUI.cs
Fixed case when having more than 1000 entries in one queue and starting offset bigger than 0.
For example: in a project look for some entry with more than 1000 results, and try to look again for it, since the limit is set to 1000, but the tracelog count is well above 1000, the user won't see the right results.
> Fix Results display

- External/Plugins/CodeRefactor/PluginMain.cs
> Disables the "Extract local variable..." if the selected text is outside the function

- External/Plugins/ASCompletion/ASCompletion.csproj
- External/Plugins/ASCompletion/Model/ASFileParser.cs
- Tests/External/Plugins/ASCompletion.Tests/ASCompletion.Tests.csproj
- Tests/External/Plugins/ASCompletion.Tests/Model/ASFileParserTests.cs
- Tests/External/Plugins/ASCompletion.Tests/Test Files/parser/haxe/FunctionTypesAsArgumentsTest.hx
- Tests/External/Plugins/ASCompletion.Tests/Test Files/parser/haxe/KeywordAndUnderscoreInNameTest.hx
* Do not treat _ in an identifier as a separator, this causes unneeded extra parsing, but also problems if a subpart of the name happens to be a keyword.
* Finalize correctly function types when they are arguments.
* Detect when a generic is inside a function type, that starts with a subtype.
This fixes issue #1141, fixes issue #1125 and an extra problem.
> Parsing improvements

- External/Plugins/HaXeContext/Completion/HaxeComplete.cs
- External/Plugins/HaXeContext/Context.cs
The +1 that was required here previously was actually a Haxe debug fixed recently on the dev branch, which now leads to incorrect results without the version check.
Sci.WordEndPosition() is technically not required on latest Haxe anymore either.
> HaxeComplete: fix position / usage positions for Haxe 3.3.0

- PluginCore/PluginCore/Localization/TextHelper.cs
Changing the locale using the `Tools>Program Settings...` should require a restart to take effect.
Since some texts are retrieved on load, and some texts are retrieved as they are needed, allowing a refresh of the locale every time text is retrieved can produce something like this:
> Do not refresh locale

- External/Plugins/CodeRefactor/PluginMain.cs
Fox example:
Create new document.
Paste code.
Execute "Find all references".
Result:
> [Fix crashes] Disable "Find all references" for files that are not saved to disk.

- FlashDevelop/Bin/Debug/Projects/365 Haxe - C# Project/run.bat.template
- FlashDevelop/Bin/Debug/Projects/370 Haxe - Java Project/run.bat.template
Hello,
The line break was, uh, _breaking_ the script. Couldn't find any mention of this among open issues or pull requests, so I went ahead and fixed it.
> Removed line break before else branch of conditional in C#, Java run.bat templates.

- FlashDevelop/Dialogs/HashDialog.cs
- PluginCore/PluginCore/Utilities/CryptoClasses.cs
After installing Cisco VPN client, FlashDevelop stopped working because it's using non FIPS compliant  algorithms.
> Use FIPS 140-2 compliant algorithm if available when required

- External/Plugins/ASCompletion/Commands/CallFlashIDE.cs
Adobe Flash has been rebranded into Animate, which means FD will not detect/launch Animate.exe automatically.
This is a minimal fix, it works for me, but I'm not in the mood of rewriting the detection in a cleaner/unit tested way.
> Minimal fix to correctly locate/launch Adobe Animate

- appman.xml
I posted this extension to the [forum](http://www.flashdevelop.org/community/viewtopic.php?f=4&t=12458) a while ago, and I kinda forgot about it until now, kek.
I wasn't sure on which group to put this on, as it's not a plugin, but it's not quite a compiler either. So I put it in a new group as Extension. 
By the way, wouldn't it be easier if AppMan's Config.xml file refer to https://raw.githubusercontent.com/fdorg/flashdevelop/development/appman.xml rather than http://www.flashdevelop.org/appman.xml?
> Adding extension SwcBuild

- External/Plugins/ASCompletion/Completion/ASGenerator.cs
- Tests/External/Plugins/ASCompletion.Tests/ASCompletion.Tests.csproj
- Tests/External/Plugins/ASCompletion.Tests/Completion/ASGeneratorTests.cs
- Tests/External/Plugins/ASCompletion.Tests/Test Files/generated/as3/AfterGeneratePublicStaticFunction_forSomeType.as
- Tests/External/Plugins/ASCompletion.Tests/Test Files/generated/as3/AfterGeneratePublicStaticFunction_generateExplicitScopeIsFalse.as
- Tests/External/Plugins/ASCompletion.Tests/Test Files/generated/as3/AfterGeneratePublicStaticFunction_generateExplicitScopeIsTrue.as
- Tests/External/Plugins/ASCompletion.Tests/Test Files/generated/as3/AfterGeneratePublicStaticVariable_forCurrentType.as
- Tests/External/Plugins/ASCompletion.Tests/Test Files/generated/as3/AfterGeneratePublicStaticVariable_forSomeType.as
- Tests/External/Plugins/ASCompletion.Tests/Test Files/generated/as3/BeforeGenerateStaticFunction.as
- Tests/External/Plugins/ASCompletion.Tests/Test Files/generated/as3/BeforeGenerateStaticFunction_forCurrentType.as
- Tests/External/Plugins/ASCompletion.Tests/Test Files/generated/as3/BeforeGenerateStaticFunction_forSomeType.as
- Tests/External/Plugins/ASCompletion.Tests/Test Files/generated/as3/BeforeGenerateStaticVariable_forCurrentType.as
- Tests/External/Plugins/ASCompletion.Tests/Test Files/generated/as3/BeforeGenerateStaticVariable_forSomeType.as
- Tests/External/Plugins/ASCompletion.Tests/Test Files/generated/haxe/AfterGeneratePublicStaticVariable_forCurrentType.hx
- Tests/External/Plugins/ASCompletion.Tests/Test Files/generated/haxe/AfterGeneratePublicStaticVariable_forSomeType.hx
- Tests/External/Plugins/ASCompletion.Tests/Test Files/generated/haxe/AfterGeneratePublicStaticVariable_generateExplicitScopeIsFalse.hx
- Tests/External/Plugins/ASCompletion.Tests/Test Files/generated/haxe/AfterGeneratePublicStaticVariable_generateExplicitScopeIsTrue.hx
- Tests/External/Plugins/ASCompletion.Tests/Test Files/generated/haxe/BeforeGeneratePublicStaticVariable_forCurrentType.hx
- Tests/External/Plugins/ASCompletion.Tests/Test Files/generated/haxe/BeforeGeneratePublicStaticVariable_forSomeType.hx
- Tests/External/Plugins/ASCompletion.Tests/Test Files/generated/haxe/BeforeGenerateStaticVariable.hx
BUG in release 5.1.1, code for example:
```
package {
public class Main {
public function Main() {
Main.test|;
}
}
}
```
result after generating variable:
```
package {
public class Main {
private var test;//must be private static var test;
public function Main() {
Main.test;
}
}
}
```
BUG in developmnet version if setting generate explicit scope is true, code for example:
```
package;
public class Main {
public static function main() {
test|;
}
}
```
result after generating variable:
```
package;
public class Main {
static private var test;
public static function main() {
this.test;//must be Main.test
}
}
```
> Fixes generate static variable and generate static function

- PluginCore/PluginCore/Helpers/FileHelper.cs
`File.Exists(file) ? FileMode.Truncate : FileMode.CreateNew` is exactly how `FileMode.Create` is supposed to perform, but `FileMode.Create` fails on hidden files. More details in #1266.
Closes #1270 
Tested with hidden files -> saves without error.
Tested saving after deleting content then reloading -> file is correctly saved.
> Fixes existing files not truncated on save.

- FlashDevelop/Dialogs/SettingDialog.cs
- FlashDevelop/MainForm.cs
- FlashDevelop/Settings/Accessors.cs
- PluginCore/PluginCore/Interfaces.cs
- PluginCore/PluginCore/Localization/Attributes.cs
I think it's good to let users know which settings take effect only after a restart. 
Really simple syntax for developers: just add a `[RequiresRestart]` attribute.
> Notify Restart Required on Settings Change

- External/Plugins/HaXeContext/Completion/HaxeComplete.cs
- External/Plugins/HaXeContext/ExternalToolchain.cs
- External/Plugins/ProjectManager/Projects/Haxe/HaxeProject.cs
- Parse hxml files used inside other hxml files. Doing this results in better project support: classpaths, finding --next statements inside other hxml, etc. I know the code is not very nice because of the method signature, but it's private code, so it's not harmful.
- When parsing the hxml file don't count next lines starting with # as the parameter of a previous command. For example having this inside the hxml could lead to wrong compiler service calling:
```
-debug
#comment
```
- When constructing the compiler command line from the project properties also quote lines for -cmd commands. Having something like -cmd bin/test.bat could break compiler service calling. Maybe we should also quote -x commands. Another option could be maybe to remove these commands, but I don't know if removing …
> Fixes when using hxml

- External/Plugins/ProjectManager/Projects/ProjectReader.cs
- External/Plugins/ProjectManager/Projects/ProjectWriter.cs
Fix project building on Linux when directory path contains "%2f" (escaped forward slash symbol)
> [FDBuild] Fix project building on Linux when directory path contains %2f

- PluginCore/DockPanelSuite/Customization/VS2005DockPaneStrip.cs
- PluginCore/PluginCore/Helpers/PathHelper.cs
Current rendering method is a sh*t:
The problem is that in order to draw the text in the tabs the code is using TextRenderer with TextFormatFlags.PathEllipsis, and it only removes full path parts, nothing else... which is useless with long filenames... Because of that latest DockPanelSuite releases modified it to use TextFormatFlags.EndEllipsis, which results in this:
Which is not very nice either, it's not uncommon to have multiple files with similar starts of filenames, or the same filenames but different extensions. Hence I decided to play a bit with different things to come up with this one which I think it's better for everyone:
StringTrimming.PathEllipsis used with Graphics.DrawString is able to render this case in a similar way to this custom implementation... but if you google you …
> Custom method to compact the text of document tabs with long filenames

- External/Plugins/AirProperties/Forms/AirWizard.cs
> Fixed wrong cast causing iOS UIBackgroundModes in AIR descriptor file to not be filled correctly.

- External/Plugins/FlashDebugger/Controls/DataTipForm.cs
- External/Plugins/FlashDebugger/Controls/DataTreeControl.cs
- External/Plugins/FlashDebugger/Controls/LiveDataTip.cs
- Delay initializing DataTreeControl in DataTipForm until theming has been loaded
- Apply DataTreeControl ForeColor and BackColor theming
- Size DataTipForm based on AutoHeightRowLayout Bounds height for rows since TreeViewAdv.RowSize doesn't return the value based on AutoHeight being applied
- Default DataTipForm Column widths based on the width of their Header text
Problem:
> Theme and Size LiveDataTip

- External/Plugins/ASCompletion/PluginMain.cs
This line was removed after #1245, but after #1316 this is required again.
Note: added in [`aa65d56`](https://github.com/fdorg/flashdevelop/pull/947/commits/aa65d56649d2d801294e7f8ab8e14ef7ab45891c#diff-fa9c2f4eb75fd264db1491c03499a09cR756), removed in [`ef958cf`](https://github.com/fdorg/flashdevelop/pull/947/commits/ef958cf1e64e0d19316d4c7575d9c85eea8c18f3#diff-fa9c2f4eb75fd264db1491c03499a09cL756)
> AddClosingBraces small fix

- External/Plugins/ASCompletion/Completion/ASGenerator.cs
- Tests/External/Plugins/ASCompletion.Tests/ASCompletion.Tests.csproj
- Tests/External/Plugins/ASCompletion.Tests/Completion/ASGeneratorTests.cs
- Tests/External/Plugins/ASCompletion.Tests/MainForm.cs
- Tests/External/Plugins/ASCompletion.Tests/Test Files/generated/haxe/AfterOverrideGetNull.hx
- Tests/External/Plugins/ASCompletion.Tests/Test Files/generated/haxe/AfterOverrideGetSet.hx
- Tests/External/Plugins/ASCompletion.Tests/Test Files/generated/haxe/AfterOverrideNullSet.hx
- Tests/External/Plugins/ASCompletion.Tests/Test Files/generated/haxe/BeforeOverrideGetNull.hx
- Tests/External/Plugins/ASCompletion.Tests/Test Files/generated/haxe/BeforeOverrideGetSet.hx
- Tests/External/Plugins/ASCompletion.Tests/Test Files/generated/haxe/BeforeOverrideNullSet.hx
Overriding the property is only valid for accessor methods of reading and / or writing
but the Editor generate override of property without access methods.
code for example:
```haxe
var foo(get, never):T
```
actual result after generate override:
```haxe
//@:getter(foo)
override function get_foo():T
{
return super.get_foo();
}
//@:setter(foo)
override function set_foo(value:T):T
{
return super.set_foo(value);
}
```
expected result:
```haxe
//@:getter(foo)
override function get_foo():T
{
return super.get_foo();
}
```
Fixed generation of override setter, actual:
```haxe
//@:setter(foo)
override function set_foo(value:T):T
{
return set_foo(value);
}
```
expected:
```haxe
//@:setter(foo)
override function set_foo(value:T):T
{
return super.set_foo(value);
}
```
> [Haxe] Fixed generation of override of property.

- PluginCore/PluginCore/Controls/CompletionList.cs
Resolves #1138
There was a max width defined for the completion list of 400 pixels regardless of scaling. Changed to use ScaleHelper.Scale so that this max width will be larger on HiDPI displays. Since there is a max width, there is still the chance that long namespaces will cause suggestions to be cut off, however the completion list should render consistently despite different DPIs.
> Scale the max width of the CompletionList

- External/Plugins/ProjectManager/Projects/ProjectWriter.cs
Use FileMode.Truncate/FileMode.CreateNew instead of FileMode.OpenOrCeate when saving project files. (fixes #1330)
> Fixed project saving

- External/Plugins/ProjectManager/Projects/Haxe/HaxeProject.cs
For example having inside a hxml lines like:
#Comment -js
Would set the -js target.
Or having:
./build--next.hxml
Would interpret the line as a --next argument and stop parsing the current file.
> [HXML] Fixed parsing of lines that are not arguments with '-' in the middle.

- appman.xml
https://github.com/HaxeFlixel/flixel/issues/1753#issuecomment-244669230
Package' archive is hosted on peyty.github.io
Any issues?
> HaxeFlixel Demos added to appman

- Tests/External/Plugins/CodeRefactor.Tests/Commands/CodeRefactorTests.cs
If they are intended to become supported cases in the future add them back.
> Ignore tests that were never working.

- CI/tests.ps1
- Tests/External/Plugins/ASCompletion.Tests/ASCompletion.Tests.csproj
- Tests/External/Plugins/ASCompletion.Tests/packages.config
- Tests/External/Plugins/CodeRefactor.Tests/Commands/CodeRefactorTests.cs
If you ever decide to update NUnit or NSubstitute make sure every testing assembly uses the same one or make sure the changes won't conflict!
> Use the same NSubsitute version in every test assembly

- External/Plugins/HaXeContext/Context.cs
Building a virtual HXML is a problem, because if rawHxml is set it will return that, and if libs are defined in HXMLs inside other HXMLs this info gets lost, causing some FD features to not work properly.
I don't know why we'd want to return a virtual HXML, I checked and it's quite old code, so maybe it was needed back in the day... nowadays I don't see a need for doing it that way?
> Get Haxe libraries from project CompilerOptions instead of building virtual HXML

- PluginCore/ScintillaNet/ScintillaControl.cs
- PluginCore/ScintillaNet/Structs.cs
Right now there are a lot of code that needs to get arbitrary ranges of text from Scintilla, and people are using sci.GetSel() + sci.SelText, this is not very nice... plus also forces the people to store the previous selection indexes...
I saw there is also a SCI_GETRANGEPOINTER function in Scintilla that may be marginally faster, but I don't know if our version already supports it.
> Added GetTextRange function to ScintillaControl

- External/Plugins/AS3Context/Context.cs
- External/Plugins/HaXeContext/Context.cs
Useful for plugins and some other cases.
> Don't fail if we don't have a CurrentModel when calling Context.GetAllProjectClasses()

- FlashDevelop/Docking/TabbedDocument.cs
If the file's read-only property changes, the Scintilla instance is not updated to reflect the change. This means you could continue to edit the file without anything knowing that the file is actually read-only now. This causes issues with some plugins (namely the Perforce plugin) that need to handle edits to a read-only file.
For example, if you use the Perforce plugin to checkout a file through FD, and then revert the file through Perforce outside of FD, FD will never know that the revert happened. This causes it to think that the file is still checked out, which breaks the plugin and gets it in a confused state where it doesn't auto-checkout on edit anymore.
Addtionally, when reloading a file, it doesn't update the fileInfo instance, which means that you can technically reload a file …
> Reload file on read-only property change

- FlashDevelop/Dialogs/FRInDocDialog.cs
> ScintillaControl.ReplaceTarget uses replacement length, not source.

- External/Plugins/ProjectManager/Projects/ProjectReader.cs
Currently, an exception will be thrown if you attempt to open a FD project files that is read-only. This is a problem when using source control programs like Perforce that force everything to read-only if you aren't editing them.
This fix will allow FD to open the project as normal. You won't be able to edit it in any way, but it gives you a clear error when you try so it's not an issue.
> Fix project open to support read-only files

- External/Plugins/ASCompletion/Completion/ASComplete.cs
- External/Plugins/ASCompletion/PluginMain.cs
- PluginCore/PluginCore.csproj
- PluginCore/PluginCore/Controls/CodeTip.cs
- PluginCore/PluginCore/Controls/UITools.cs
- PluginCore/PluginCore/Utilities/DataConverter.cs
resolves #1019 
When hovering over a member with the control key pressed a CodeTip will popup displaying the lines of code where the member is defined.
> Implemented CodePeek on Ctrl+Hover

- FlashDevelop/Dialogs/FRInDocDialog.cs
- FlashDevelop/Dialogs/FRInFilesDialog.cs
- FlashDevelop/Docking/TabbedDocument.cs
- FlashDevelop/MainForm.cs
When opening the find-and-replace dialog the first time it automatically populates the find text with whatever you have selected. Every additional attempt will no longer update the text.
This change makes it so every time you activate the dialog, usually through Ctrl+Shift+F, it will update the find text to use whatever you had selected at the time, making it much easier to use.
> Fill the find-and-replace text with current selection every time it's activated

- External/Plugins/ASCompletion/Completion/ASComplete.cs
- PluginCore/PluginCore/Controls/CompletionList.cs
- If we are instantiating an nonexistent item add it to the list and notify about its missing state.
- If we are instantiating a generic type, add it with the index type to the list.
This closes #71.
Sample:
EDIT: There are some artifacts in the GIF for some reason.
> Improve completion after new

- External/Plugins/OutputPanel/PluginMain.cs
- External/Plugins/OutputPanel/Settings.cs
- PluginCore/PluginCore/Resources/de_DE.resX
- PluginCore/PluginCore/Resources/en_US.resX
- PluginCore/PluginCore/Resources/eu_ES.resX
- PluginCore/PluginCore/Resources/ja_JP.resX
- PluginCore/PluginCore/Resources/ko_KR.resX
- PluginCore/PluginCore/Resources/zh_CN.resx
This is useful for many cases. One case:
- I have a Haxe project. I run it and the build starts. Output panel cleared.
- During the build I have some macros that outputs some stuff.
- The build finishes and I have for running the project another process. The output panel is cleared again and I lose the traces from the macros.
Another one:
- I have important stuff in the output panel.
- I run a FD macro. I lose the stuff in the output panel.
> Setting to define when to clear the output panel.

- External/Plugins/CodeRefactor/Commands/OrganizeImports.cs
- Tests/External/Plugins/CodeRefactor.Tests/CodeRefactor.Tests.csproj
- Tests/External/Plugins/CodeRefactor.Tests/Commands/CodeRefactorTests.cs
- Tests/External/Plugins/CodeRefactor.Tests/Test Files/coderefactor/organizeimports/haxe/AfterOrganizeImports_withImportsFromSameModule2.hx
- Tests/External/Plugins/CodeRefactor.Tests/Test Files/coderefactor/organizeimports/haxe/BeforeOrganizeImports_withImportsFromSameModule2.hx
Fixed `Object reference not set to an instance of an object.`
at CodeRefactor.Commands.OrganizeImports.ContainsMember(FileModel file, MemberModel member)
at CodeRefactor.Commands.OrganizeImports.ExecutionImplementation()
at CodeRefactor.PluginMain.OrganizeImportsClicked(Object sender, EventArgs e)
> [CodeRefactor. OrganizeImports] Fixed `Object reference not set to an instance of an object.`

- External/Plugins/ASCompletion/Completion/ASGenerator.cs
- Tests/External/Plugins/ASCompletion.Tests/Completion/ASGeneratorTests.cs
Fixes issue #1397
This function should be changed in the near future to use normal positions instead of lines to support more than a function per line. Although better yet if could also use a model and support single line functions without brackets.
> Do not consider { as the start of a body if we are inside parenthesis

- External/Plugins/CodeRefactor/Commands/Rename.cs
code for example:
```actionscript
package {
import flash.display.Sprite;
public class Main extends Sprite {
public function Main(value:String) {
v = value;
trace(v);
}
private var v:String;
}
}
```
Expected result after rename `value` to `v`:
```actionscript
package {
import flash.display.Sprite;
public class Main extends Sprite {
public function Main(v:String) {
this.v = value;
trace(this.v);
}
private var v:String;
}
}
```
Actual result after rename `value` to `v`:
```actionscript
package {
import flash.display.Sprite;
public class Main extends Sprite {
public function Main(v:String) {
this.v = value;
trace(this.v);
}
private var this.v:String;// <-- BUG: this.v should be v
}
}
```
> Fixed fails after renaming when renaming function parameters in some cases. part2 #467

- External/Plugins/TaskListPanel/PluginUI.cs
- FlashDevelop/Dialogs/SettingDialog.cs
- When saving settings show wait cursor to avoid people on slow systems to think they didn't successfully click on Close.
- TaskList Panel status bar was showing the resize indicator when the main form was not maximized.
> Minor UI tweaks

- External/Plugins/ASCompletion/Completion/ASGenerator.cs
- Tests/External/Plugins/ASCompletion.Tests/ASCompletion.Tests.csproj
- Tests/External/Plugins/ASCompletion.Tests/Completion/ASGeneratorTests.cs
- Tests/External/Plugins/ASCompletion.Tests/Test Files/generated/as3/AfterAssignStatementToVarFromArrayInitializer2_useSpaces.as
- Tests/External/Plugins/ASCompletion.Tests/Test Files/generated/as3/AfterAssignStatementToVarFromArrayInitializer_useSpaces.as
- Tests/External/Plugins/ASCompletion.Tests/Test Files/generated/as3/AfterAssignStatementToVarFromFunctionResult_useSpaces.as
- Tests/External/Plugins/ASCompletion.Tests/Test Files/generated/as3/AfterAssignStatementToVarFromNewBitmapDataWithParams_multiline_useSpaces.as
- Tests/External/Plugins/ASCompletion.Tests/Test Files/generated/as3/AfterAssignStatementToVarFromNewBitmapDataWithParams_useSpaces.as
- Tests/External/Plugins/ASCompletion.Tests/Test Files/generated/as3/AfterAssignStatementToVarFromNewString2_useSpaces.as
- Tests/External/Plugins/ASCompletion.Tests/Test Files/generated/as3/AfterAssignStatementToVarFromNewString_useSpaces.as
- Tests/External/Plugins/ASCompletion.Tests/Test Files/generated/as3/BeforeAssignStatementToVarFromArrayInitializer2_useSpaces.as
- Tests/External/Plugins/ASCompletion.Tests/Test Files/generated/as3/BeforeAssignStatementToVarFromArrayInitializer_useSpaces.as
- Tests/External/Plugins/ASCompletion.Tests/Test Files/generated/as3/BeforeAssignStatementToVarFromFunctionResult_useSpaces.as
- Tests/External/Plugins/ASCompletion.Tests/Test Files/generated/as3/BeforeAssignStatementToVarFromNewBitmapDataWithParams_multiline_useSpaces.as
- Tests/External/Plugins/ASCompletion.Tests/Test Files/generated/as3/BeforeAssignStatementToVarFromNewBitmapDataWithParams_useSpaces.as
- Tests/External/Plugins/ASCompletion.Tests/Test Files/generated/as3/BeforeAssignStatementToVarFromNewString2_useSpaces.as
- Tests/External/Plugins/ASCompletion.Tests/Test Files/generated/as3/BeforeAssignStatementToVarFromNewString_useSpaces.as
Fixes `new BitmapData(rect.width, rect.height) -> new var bitmapData:BitmapData(rect.width, rect.height)`
Fixes assign statement to local variable from multilime constructor, for example:
```actionscript
new BitmapData(
rect.width,
rect.height
) | <<- cursor here
```
> Improve `Assign statement to local variable`

- External/Plugins/ASCompletion/Completion/ASGenerator.cs
- Tests/External/Plugins/ASCompletion.Tests/ASCompletion.Tests.csproj
- Tests/External/Plugins/ASCompletion.Tests/Completion/ASGeneratorTests.cs
- Tests/External/Plugins/ASCompletion.Tests/Test Files/generated/as3/AfterAssignStatementToVarFromCallback_useSpaces.as
- Tests/External/Plugins/ASCompletion.Tests/Test Files/generated/as3/BeforeAssignStatementToVarFromCallback_useSpaces.as
Before fix:
```actionscript
function test() {
foo | <-- cursor here
}
function foo():Number {return 1;}
```
Result
```actionscript
function test() {
var f:Function = foo
}
function foo():Number {return 1;}
```
Actual for the current release
> Assign statement of callback to var local variable

- External/Plugins/ASCompletion/Completion/ASGenerator.cs
- External/Plugins/ASCompletion/Completion/TemplateUtils.cs
- Tests/External/Plugins/ASCompletion.Tests/ASCompletion.Tests.csproj
- Tests/External/Plugins/ASCompletion.Tests/Completion/ASGeneratorTests.cs
- Tests/External/Plugins/ASCompletion.Tests/Test Files/generated/haxe/AfterOverrideFunctionWithTypeParams.hx
- Tests/External/Plugins/ASCompletion.Tests/Test Files/generated/haxe/BeforeOverrideFunctionWithTypeParams.hx
- Tests/External/Plugins/ASCompletion.Tests/Test Files/generated/haxe/ImplementInterfaceNoMembers.hx
Import of types used in constraints and spaces between params may be removed, but it's not considered as important right now.
@SlavaRa  Any concern with this?
> Fixed generation and override of functions with type parameters.

- External/Plugins/CodeRefactor/Provider/RefactoringHelper.cs
Error log:```Object reference not set to an instance of an object.
at CodeRefactor.Provider.RefactoringHelper.FindTargetInFiles(ASResult target, FRProgressReportHandler progressReportHandler, FRFinishedHandler findFinishedHandler, Boolean asynchronous, Boolean onlySourceFiles, Boolean ignoreSdkFiles, Boolean includeComments, Boolean includeStrings)
at CodeRefactor.Commands.Move.UpdateReferencesNextTarget()
at CodeRefactor.Commands.Move.ExecutionImplementation()
at CodeRefactor.Provider.MovingHelper.ExecuteFirst()```
> Fixes "Object reference not set to an instance of an object." after Refactor > Move

- External/Plugins/CodeRefactor/Provider/RefactoringHelper.cs
```
at CodeRefactor.Provider.RefactoringHelper.FindTargetInFiles(ASResult target, FRProgressReportHandler progressReportHandler, FRFinishedHandler findFinishedHandler, Boolean asynchronous, Boolean onlySourceFiles, Boolean ignoreSdkFiles, Boolean includeComments, Boolean includeStrings)
at CodeRefactor.Commands.FindAllReferences.ExecutionImplementation()
at CodeRefactor.Commands.Rename.ExecutionImplementation()
at CodeRefactor.Provider.RenamingHelper.ExecuteFirst()
```
I will do tests for this helper next week. Today I checked all renames manually
> Fixes "Object reference not set to an instance of an object."

- External/Plugins/SourceControl/Actions/TreeContextMenuUpdate.cs
- External/Plugins/SourceControl/Helpers/AnnotatedDocument.cs
- External/Plugins/SourceControl/Helpers/Commit.cs
- External/Plugins/SourceControl/PluginMain.cs
- External/Plugins/SourceControl/SourceControl.csproj
- External/Plugins/SourceControl/Sources/Git/BaseCommand.cs
- External/Plugins/SourceControl/Sources/Git/BlameCommand.cs
- External/Plugins/SourceControl/Sources/Git/MenuItems.cs
- External/Plugins/SourceControl/Sources/Git/TortoiseProc.cs
- External/Plugins/SourceControl/Sources/IVCManager.cs
- External/Plugins/SourceControl/Sources/Mercurial/MenuItems.cs
- External/Plugins/SourceControl/Sources/Subversion/MenuItems.cs
- FlashDevelop/MainForm.cs
- PluginCore/PluginCore/Controls/UITools.cs
- PluginCore/ScintillaNet/Configuration/Language.cs
- PluginCore/ScintillaNet/Configuration/StyleClass.cs
- PluginCore/ScintillaNet/Enums.cs
- PluginCore/ScintillaNet/Events.cs
- PluginCore/ScintillaNet/ScintillaControl.cs
Added integrated support for "blame" feature. Currently only added support for git.
Support for other vcs plugins can be added by following the pattern used in Sources/Git/BlameCommand.
Example:
@Neverbirth
> SourceControl intergrated blame

- PluginCore/PluginCore/Controls/CompletionList.cs
```
at System.String.InternalSubStringWithChecks(Int32 startIndex, Int32 length, Boolean fAlwaysCopy)
at System.String.Substring(Int32 startIndex, Int32 length)
at PluginCore.Controls.CompletionList.HandleKeys(ScintillaControl sci, Keys key) in C:\projects\flashdevelop\PluginCore\PluginCore\Controls\CompletionList.cs:line 890
at PluginCore.Controls.UITools.HandleKeys(Keys key) in C:\projects\flashdevelop\PluginCore\PluginCore\Controls\UITools.cs:line 441
at PluginCore.Controls.UITools.HandleEvent(Object sender, NotifyEvent e, HandlingPriority priority) in C:\projects\flashdevelop\PluginCore\PluginCore\Controls\UITools.cs:line 138
at PluginCore.Managers.EventManager.DispatchEvent(Object sender, NotifyEvent e) in C:\projects\flashdevelop\PluginCore\PluginCore\Managers\EventManager.cs:line …
```
> Fixed exception: "Length cannot be less than zero. Parameter name: length"

- PluginCore/ScintillaNet/ScintillaControl.cs
- Tests/External/Plugins/CodeRefactor.Tests/Commands/CodeRefactorTests.cs
Fix ScintillaControl.CurLineSize and GetCurLine()
Change CommandFactoryProvider.GetFactoryFromLanguage to GetFactory in
CodeRefactorTests.cs
Required for #1519
> Small fixes

- FlashDevelop/Dialogs/SettingDialog.cs
- PluginCore/PluginCore/Localization/Attributes.cs
Search filter checks the property name, display name, category and description, using current culture with ignore case.
Closes #1151 
Closes #1193
> SettingsDialog search filter improvements

- External/Tools/SetVersion/Program.cs
Should i also commit compiled SetVersion.exe?
> SetVersion: Path.DirectorySeparatorChar instead of hardcoded backslash

- External/Plugins/ASCompletion/Completion/ASComplete.cs
- External/Plugins/ASCompletion/Completion/Brace.cs
- External/Plugins/ASCompletion/Controls/AddClosingBracesRulesEditorForm.cs
- External/Plugins/ASCompletion/Settings/GeneralSettings.cs
- PluginCore/ScintillaNet/ScintillaControl.cs
- Tests/External/Plugins/ASCompletion.Tests/Completion/ASCompleteTests.cs
Ignore Whitespace setting
Rather than ignoring whitespace globally, allow individual settings.
Features:
- Overwrite closing with whitespace in the middle (`' '` or `'\t'`)
**Add `}`:**
Result: ![1-3](https://cloud.githubusercontent.com/assets/13545633/25289066/1fcb5098-2703-11e7-8d42-242566cd6e21.PNG) Before: ![1-4](https://cloud.githubusercontent.com/assets/13545633/25289071/26861dd2-2703-11e7-885e-b420eea29685.PNG)
- Delete matching closing brace with whitespace in the middle (`char.IsWhiteSpace()`)
**Backspace:**
Result: ![1-6](https://cloud.githubusercontent.com/assets/13545633/25289147/72eb3644-2703-11e7-9317-4c6d400ee2ac.PNG) Before: ![1-7](https://cloud.githubusercontent.com/assets/13545633/25289156/7b9907da-2703-11e7-8669-86ffacba484b.PNG)
**Also deletes new line characters:** …
> Extra options for AddClosingBraces

- PluginCore/ScintillaNet/ScintillaControl.cs
Sets `DataFormats.Text` or `DataFormats.UnicodeText` data as well as `DataFormats.RTF` data on copy.
Added `CutRTF()`.
Added `Cut/CopyAllowLine()` and `Cut/CopyAllowLineEx()` methods.
> CopyRTF improvements

- External/Plugins/ASCompletion/Completion/ASGenerator.cs
- Tests/External/Plugins/ASCompletion.Tests/ASCompletion.Tests.csproj
- Tests/External/Plugins/ASCompletion.Tests/Completion/ASGeneratorTests.cs
- Tests/External/Plugins/ASCompletion.Tests/Test Files/generated/as3/AfterAssignStatementToVarFromUnsafeCastExpr.as
- Tests/External/Plugins/ASCompletion.Tests/Test Files/generated/as3/BeforeAssignStatementToVarFromUnsafeCastExpr.as
```
at System.Linq.Enumerable.Last[TSource](IEnumerable`1 source)
at ASCompletion.Completion.ASGenerator.GetStatementReturnType(ScintillaControl sci, ClassModel inClass, String line, Int32 startPos)
at ASCompletion.Completion.ASGenerator.AssignStatementToVar(ClassModel inClass, ScintillaControl sci, MemberModel member)
at ASCompletion.Completion.ASGenerator.GenerateJob(GeneratorJobType job, MemberModel member, ClassModel inClass, String itemLabel, Object data)
at ASCompletion.Completion.GeneratorItem.get_Value()
at PluginCore.Controls.CompletionList.ReplaceText(ScintillaControl sci, String tail, Char trigger)
at PluginCore.Controls.CompletionList.HandleKeys(ScintillaControl sci, Keys key)
at PluginCore.Controls.UITools.HandleKeys(Keys key)
at PluginCore.Controls.UITools.HandleEvent(Object …
```
> Fixed "Sequence contains no elements"

- FlashDevelop/Managers/ClipboardManager.cs
Another solution (checks if Vista or higher): instead of `Win32.ShouldUseWin32()`
```c#
Environment.OSVersion.Platform == PlatformID.Win32NT && Environment.OSVersion.Version > 5
```
But since this is more about whether a certain function is available, I think checking for `EntryPointNotFoundException` makes more sense.
Closes #1621
> Check for missing AddClipboardFormatListener entry point

- External/Plugins/ResultsPanel/Helpers/ResultsPanelHelper.cs
- External/Plugins/ResultsPanel/ListViewEx.cs
- External/Plugins/ResultsPanel/PluginMain.cs
- External/Plugins/ResultsPanel/PluginUI.cs
- External/Plugins/ResultsPanel/Settings.cs
- PluginCore/PluginCore/Resources/de_DE.resx
- PluginCore/PluginCore/Resources/en_US.resx
- PluginCore/PluginCore/Resources/eu_ES.resx
- PluginCore/PluginCore/Resources/ja_JP.resx
- PluginCore/PluginCore/Resources/ko_KR.resx
- PluginCore/PluginCore/Resources/zh_CN.resx
- Added `KeepResultsByDefault` setting.
- View Menu for multiple panels as a drop down.
- Note that hidden panels are present in the drop down list. However closed panels are not.
- Sorting improved:
- You can now sort by line numbers.
- Sorting by line numbers or descriptions does not group the entries.
- This is because their values are likely to be all unique, thus it will only create groups with only one or two entries otherwise.
- `DefaultGrouping` setting does not affect panels that already exist anymore.
- `HighlightOnlyActivePanelEntries` setting defaults to `false`.
- Bug fixes:
- `RefreshSquiggles()` should respect the settings.
- Only refresh when related settings have changed.
Closes #1596 
Related to issue 1 in #1601
> ResultsPanel Improvements v2

- FlashDevelop/MainForm.cs
When the method is overloaded, ScintillaCommand throws an exception without parameter types explicitly specified.
> Fix ScintillaCommand exception with overloaded methods

- External/Plugins/HaXeContext/Completion/HaxeComplete.cs
- External/Plugins/HaXeContext/Linters/DiagnosticsLinter.cs
- External/Plugins/LintingHelper/Managers/LintingManager.cs
- External/Plugins/ResultsPanel/PluginUI.cs
- PluginCore/ScintillaNet/Configuration/EditorStyle.cs
Instead of directly accessing scintilla highlighting api from LintingHelper, let ResultsPanel manage all highlighting.
Also change the default colour of warning (`DebugLineBack`) to orange from yellow, since it was barely visible with a default white background.
> Refactoring for highlights management

- FlashDevelop/Docking/DockablePanel.cs
- FlashDevelop/MainForm.cs
When a new DockablePanel is added, it shown immediately before it's DockState is set. This causes it to be added to the right (where the Outline, Project, etc. panel are in the default layout) and then moved to the correct place immediately. However, this means, the focus of the "tabbed" panels on the right will change to the first one (instead of where it was before).
This PR should fix this behaviour.
> Fix new results panel affecting other panel's layout

- FlashDevelop/MainForm.cs
- FlashDevelop/Managers/LayoutManager.cs
Copy paste from the commit message:
>Panels created using CreateDockablePanel() are expected to be created
during plugin initialization, which is right before
LayoutManager.BuildLayoutSystems(). That method ensures that all panels
are in the correct place, and shows unregistered panels as floating,
essentially making the call to Show() in CreateDockablePanel()
unnecessary.
Panels created using CreateDynamicPersistDockablePanel() are also called
LayoutManager.SetContentLayout(), which ensures the panel is in the
correct place if registered. Adding Show() at the end ensures the panel
is shown when the panel information isn't stored in the layout file.
`dockablePanel.Show()` in `CreateDynamicPersistDockablePanel()` was causing the panel to be activated upon creation, even when the panel was …
> Prevent dynamic persist panel from force-activating

- FlashDevelop/Dialogs/ClipboardHistoryDialog.cs
`preview`: RichTextBox -> TextBox
`preview.ShortcutsEnabled`: false -> true
Added `btnCopy`
`using` block around the StringFormat
> Allow copying from the ClipboardHistory dialog

- PluginCore/PluginCore/Managers/EventManager.cs
Fixes the bug on `RemoveEventHandler()` which checks for equality of two instances of `EventObject` which would never be `true`.
Also, the `try...catch` block is moved to wrap each `HandleEvent()` calls to prevent an exception from stopping the whole event dispatch process.
Includes some more refactoring.
> EventManager refactored

- PluginCore/ScintillaNet/ScintillaControl.cs
`Clear()` is the method that gets executed when Del key is pressed.
> ScintillaControl.DeleteForward() should call Clear()

- External/Plugins/ProjectManager/Controls/OpenResourceForm.cs
- Tests/External/Plugins/ProjectManager.Test/Controls/OpenResourceFormTests.cs
You can now fuzzy match folders too.
They are scored independently and the folder is higher priority.
Example:
> OpenResource dialog improvements

- External/Plugins/ProjectManager/Controls/OpenResourceForm.cs
These days many Windows tools support both `\` and `/` as the path separator - including even `Explorer` and `cmd`. On my US layout keyboards `/` is more conveniently located, also using `/` is a die-hard Linux habit of mine. Can't see any cons to making this change.
> Open Resource form: Allow `/` as path separator

- External/Plugins/HaXeContext/Context.cs
- First change is needed to not fail if the haxe directory has a dot in it (e.g.: "haxe-3.4.0" is a valid folder name)
- Second change adds support for local repositories
@SlavaRa is this alright or was there a specific reason you were using GetExtension?
> Fixes for haxelib auto install feature

- External/Plugins/ProjectManager/Projects/BuildEventVars.cs
- External/Tools/FDBuild/FDBuild.csproj
Fixes problems in 64 bits and closes #1671.
New method is based on compile time information, it could still be runtime, but I don't see any point for it.
> Modify resolution of BaseDir, FDBuild and ToolsDir build variables

- PluginCore/ScintillaNet/ScintillaControl.cs
- Make the operation simpler by not taking the language syntax into account, also avoiding numerous bugs. Closes #1626.
- Keep the current cursor selection after the operation.
Things to note:
- The last line is not movable.
- Our version of scintilla does not store cursor position in undo history, meaning undo will set the cursor to the first operation, which is `Clear()`, rather than back to the original position.
- After moving `aaaaaa` down: 
Pressing undo will put cursor after `bbbbbb`:
- After moving `bbbbbb` up:
Pressing undo will put cursor after `aaaaaa`:
- Redo is equally weird.
> Scintilla MoveLineUp/Down rewritten

- External/Plugins/ASCompletion/PluginMain.cs
- FlashDevelop/Managers/ScintillaManager.cs
- Documents without inheritance markers do not jump to the right anymore after opening
- Some double calls fixed
- Fixes a problem where breakpoint markers are shown in the inheritance margin
> Some fixes for inheritance navigation

- External/Plugins/ProjectManager/Controls/OpenResourceForm.cs
Focus textbox on Resources form when activating.
Add Ctrl+R shortcut for refreshing resource form.
This is similar to what was on previous FD versions, but slightly more optimized. Also added shortcut, that was not on the original issue, but also requested by Gene and I guess makes sense.
> Some Resources form changes (fixes #1810)

- PluginCore/PluginCore/Controls/UITools.cs
The existing logic is hacky, and should be completely replaced by something else... this topic was already raised 1.5 years ago.
I see this list was updated recently, but I never realized about how bad it is.
If the decoupled completion list is ever merged (I should update the PR with all my latest work...), this logic could be completely removed I think.
Unless we remove this check, we should be careful with any PR or even plugins dispatching "Command" events.
> Add more exceptions to UITools.HandleEvent to not hide CompletionList.

- External/Plugins/CodeRefactor/Provider/RefactoringHelper.cs
before fix:
after fix:
I will do make unit tests for this in next week
> [CodeRefactor][Rename][Haxe] Small improvement renaming of expressions whose type is some Enum

- External/Plugins/HaXeContext/Completion/CompilerCompletionHandler.cs
- External/Plugins/HaXeContext/Completion/CompletionServerCompletionHandler.cs
- External/Plugins/HaXeContext/Context.cs
- External/Plugins/HaXeContext/HaXeContext.csproj
- External/Plugins/HaXeContext/Linters/DiagnosticsLinter.cs
- External/Plugins/LintingHelper/ILintProvider.cs
- External/Plugins/LintingHelper/Managers/LintingManager.cs
- External/Plugins/LintingHelper/PluginMain.cs
- External/Plugins/ProjectManager/PluginMain.cs
- FlashDevelop/Docking/TabbedDocument.cs
- PluginCore/PluginCore/Helpers/ProcessHelper.cs
Changed Haxe process creation so calling the compiler on normal compiler completion mode is thread safe.
New ProjectSetUp event.
Changed the signature of ILintProvider to use IEnumerable<string> instead of string[] as it's not really needed and is less convenient. Also done some small optimizations.
Some better handling of starting async processes.
When linting the open files on project change, send all files together instead of individually. This has the advantage of less interruption of the main UI thread, but the problem of having to wait more for getting diagnostics. I would like to do some performance profiling in the future. I also considered using global diagnostics, but it has the problem of not taking into account files not added still in the project... but maybe this could be …
> Fixed nasty crash that may happen with diagnostics support.

- External/Plugins/AS2Context/Context.cs
- External/Plugins/AS3Context/Context.cs
- External/Plugins/HaXeContext/Context.cs
- Tests/External/Plugins/AS3Context.Tests/AS3Context.Tests.csproj
- Tests/External/Plugins/AS3Context.Tests/ContextTests.cs
- Tests/External/Plugins/AS3Context.Tests/Test Files/parser/IsImported_case1.as
- Tests/External/Plugins/AS3Context.Tests/TestUtils/TestFile.cs
- Tests/External/Plugins/ASCompletion.Tests/TestUtils/ContextExtensions.cs
- Tests/External/Plugins/HaxeContext.Tests/ContextTests.cs
- Tests/External/Plugins/HaxeContext.Tests/HaxeContext.Tests.csproj
- Tests/External/Plugins/HaxeContext.Tests/Test Files/parser/IsImported_case1.hx
- Tests/External/Plugins/HaxeContext.Tests/Test Files/parser/IsImported_case2.hx
now you can write `context.IsImported(type ?? ClassModel.VoidClass, line)` instead of `type != null && type != Class.VoidClass && context.IsImported(type, line)`
> Fixed NPE. Context.IsImported always returns false for Class.VoidClass. fixes #1930

- External/Plugins/HaXeContext/Completion/HaxeComplete.cs
Properly escape initialization macros like `--macro include("some.pack", true)`.
> Escape properly --macro commands with double quotes inside.

- External/Plugins/ASCompletion/Completion/ASComplete.cs
- Tests/External/Plugins/ASCompletion.Tests/ASCompletion.Tests.csproj
- Tests/External/Plugins/ASCompletion.Tests/Completion/ASCompleteTests.cs
- Tests/External/Plugins/ASCompletion.Tests/Test Files/completion/as3/GetExpressionType_Type_arrayInitializer.as
- Tests/External/Plugins/ASCompletion.Tests/Test Files/completion/as3/GetExpressionType_Type_as.as
- Tests/External/Plugins/ASCompletion.Tests/Test Files/completion/as3/GetExpressionType_Type_as_2.as
- Tests/External/Plugins/ASCompletion.Tests/Test Files/completion/as3/GetExpressionType_Type_is.as
- Tests/External/Plugins/ASCompletion.Tests/Test Files/completion/as3/GetExpressionType_Type_objectInitializer.as
- Tests/External/Plugins/ASCompletion.Tests/Test Files/completion/as3/GetExpressionType_Type_stringInitializer.as
- Tests/External/Plugins/ASCompletion.Tests/Test Files/completion/as3/GetExpressionType_Type_stringInitializer_2.as
- Tests/External/Plugins/ASCompletion.Tests/Test Files/completion/haxe/GetExpressionType_Type_arrayInitializer.hx
- Tests/External/Plugins/ASCompletion.Tests/Test Files/completion/haxe/GetExpressionType_Type_cast.hx
- Tests/External/Plugins/ASCompletion.Tests/Test Files/completion/haxe/GetExpressionType_Type_cast_2.hx
- Tests/External/Plugins/ASCompletion.Tests/Test Files/completion/haxe/GetExpressionType_Type_is.hx
- Tests/External/Plugins/ASCompletion.Tests/Test Files/completion/haxe/GetExpressionType_Type_mapInitializer.hx
- Tests/External/Plugins/ASCompletion.Tests/Test Files/completion/haxe/GetExpressionType_Type_stringInitializer.hx
- Tests/External/Plugins/ASCompletion.Tests/Test Files/completion/haxe/GetExpressionType_Type_stringInitializer_2.hx
- Tests/External/Plugins/ASCompletion.Tests/Test Files/completion/haxe/GetExpressionType_Type_typecheck.hx
- Tests/External/Plugins/ASCompletion.Tests/Test Files/completion/haxe/GetExpressionType_Type_typecheck_2.hx
fixes #1916
fixes https://github.com/SlavaRa/AdvancedHaxeContext/issues/3
> [ASComplete] Fixed 'ASComplete.EvalExpresion' for expression that ends with 'dot'

- External/Plugins/ASCompletion/Completion/ASComplete.cs
- External/Plugins/ASCompletion/Completion/ASGenerator.cs
- External/Plugins/ASCompletion/Context/ASContext.cs
- External/Plugins/ASCompletion/Context/IASContext.cs
- External/Plugins/ASCompletion/Model/ASFileParser.cs
- External/Plugins/ASCompletion/Model/FileModel.cs
- External/Plugins/CodeRefactor/Commands/ExtractLocalVariableCommand.cs
- External/Plugins/HaXeContext/Context.cs
- Tests/External/Plugins/ASCompletion.Tests/ASCompletionTests.cs
- Tests/External/Plugins/ASCompletion.Tests/Completion/ASGeneratorTests.cs
- Tests/External/Plugins/ASCompletion.Tests/Generators/DocumentationGeneratorTests.cs
- Tests/External/Plugins/ASCompletion.Tests/Model/ASFileParserTests.cs
- Tests/External/Plugins/ASCompletion.Tests/TestUtils/ContextExtensions.cs
- Tests/External/Plugins/HaxeContext.Tests/Generators/DocumentationGeneratorTests.cs
Now you can use:
----------------------------------------------------------------------------------------
```csharp
var fileModel = ASContext.Context.GetCodeModel(text);
```
instead of
```csharp
var fileModel = new ASFileParser().ParseSrc(new FileModel {Context = ASContext.Context, haXe = true}, text);
```
----------------------------------------------------------------------------------------
```csharp
var fileModel = ASContext.Context.GetCodeModel(fileModel, text);
```
instead of
```csharp
var fileModel = new ASFileParser().ParseSrc(fileModel, text);
```
----------------------------------------------------------------------------------------
```csharp
var fileModel = ASContext.Context.GetFileModel(fileName);
```
instead of
```csharp
var fileModel = …
```
> Improved work with the file parser.
