fdorg/flashdevelop

External/Plugins/ASCompletion/Completion/ASDocumentation.cs
PluginCore/PluginCore/Controls/UITools.cs

Fixed F1 shortcut bug when completion list visible.
More consistent (and lighter) display of the shortcut hint.

Hint shortcut

---

External/Plugins/ASCompletion/Completion/ASGenerator.cs

fixes: issue #551 Incorrect autocomplete generator behavior

---

External/Plugins/ASCompletion/Completion/ASComplete.cs
External/Plugins/ASCompletion/Context/ASContext.cs
External/Plugins/ASCompletion/Model/ASFileParser.cs
External/Plugins/ASCompletion/Model/ClassModel.cs
External/Plugins/ASCompletion/Model/FileModel.cs
External/Plugins/ASCompletion/Model/MemberModel.cs
External/Plugins/ASCompletion/Model/PathExplorer.cs
External/Plugins/ASCompletion/Model/PathModel.cs
External/Plugins/CodeRefactor/Provider/RefactoringHelper.cs

Code simplified accordingly (no need to reparse models now that they are accurate)

BinarySerializer used to store/restore models.

---

External/Plugins/AS2Context/Context.cs
External/Plugins/AS3Context/Context.cs
External/Plugins/ASCompletion/Completion/ASComplete.cs
External/Plugins/ASCompletion/Completion/ContextFeatures.cs
External/Plugins/HaXeContext/Context.cs
External/Plugins/LoomContext/Context.cs
FlashDevelop/Bin/Debug/Settings/Languages/AS3.xml

Refactored completion around accessors (public/private/inline/...) and declarations (var/function/class).

Refactored declaration completion

---

External/Plugins/ASClassWizard/PluginMain.cs
External/Plugins/ASClassWizard/Wizards/AS3ClassWizard.cs
External/Plugins/ASClassWizard/Wizards/AS3ClassWizard.designer.cs

Some cleanup, and more importantly, fixed behaviour on new file conflicts.

ASClassWizard work

---

External/Plugins/ASCompletion/CustomControls/StateSavingTreeView.cs
External/Plugins/ASCompletion/PluginUI.cs

Also, optimized the creation and update of the outline.

Treeview flicker (fd5)

---

External/Plugins/ASCompletion/CustomControls/StateSavingTreeView.cs
External/Plugins/ASCompletion/PluginUI.cs

Some more work trying to avoid flickering.
Also, optimized the creation and update of the outline.

Treeview flicker

---

External/Plugins/FlashDebugger/Debugger/ExpressionContext.cs

For example: "hello".charAt(1)

Support for expressions using string constants

---

External/Plugins/FlashDebugger/Debugger/BreakPointManager.cs
External/Plugins/FlashDebugger/Debugger/DebuggerManager.cs
External/Plugins/FlashDebugger/Helpers/ScintillaHelper.cs

Fixed breakpoint paths when there are special characters.
Fixed helper method to go to a file line, used when going to breakpoints and frames.
NOTE: Of course FD5 has some more fixes and improvements together with several new features.

Imported some debugger fixes from FD5:

---

External/Plugins/FlashDebugger/Controls/DataTree/ErrorNode.cs
External/Plugins/FlashDebugger/Controls/DataTreeControl.cs
External/Plugins/FlashDebugger/Controls/DataTreeModel.cs
External/Plugins/FlashDebugger/Controls/WatchUI.cs
External/Plugins/FlashDebugger/Debugger/ExpressionContext.cs
External/Plugins/FlashDebugger/FlashDebugger.csproj
PluginCore/PluginCore/Resources/de_DE.resX
PluginCore/PluginCore/Resources/en_US.resX
PluginCore/PluginCore/Resources/eu_ES.resX
PluginCore/PluginCore/Resources/ja_JP.resX
PluginCore/PluginCore/Resources/zh_CN.resx

Error display when evaluating expressions
Support for the Delete key.
Fixed unwatching items. It never used the right value.
Optimized adding, removing and updating entries.

Watch panel improvements

---

appman.xml

Adds NavigationBar, EditorMiniMap, CustomizeToolbar, QuickLaunch, and TrackOpenFile extensions to AppMan.

Added Plugins to AppMan.xml

---

External/Plugins/FlashDebugger/Controls/BreakPointUI.cs

Increases the width of the toolstrip buttons and controls in the Breakpoints panel.

Improve Breakpoint ToolStrip DPI scaling

---

appman.xml

Added my Visual Studio and Vibrant Ink inspired themes to the appman. I've tested them locally and believe I have the packaging of the fdz correct.

Added community themes to appman.xml

---

External/Plugins/XMLCompletion/XMLComplete.cs

I've modified the behaviour when pressing enter on XML files. The current system has some problems and may result in files with some erratic indentation, especially with multi line tags.
The new indentation mostly mimics the style of some IDEs like Visual Studio, others like Eclipse-based ones are similar but have some slight differences (if there are multiple tags in the same line or if a tag spawning to multiple lines has different indentation on each one).
I'd say the only key difference with other IDEs is the last Enter shown in the gifs, while the new code always adds a new line, other IDEs may just reindent the following closing tag. I feel adding a new line is better.
The GIF quality is not the best and there are some artifacts, but I think it shows the improvements well. Not all …

Improved smart indenting in XML completion.

---

FlashDevelop/Bin/Debug/Settings/MainMenu.xml

Better Tools->Program Settings... icon, closes #700

---

External/Plugins/CodeRefactor/Controls/RefactorMenu.cs
External/Plugins/ProjectManager/Controls/FDMenus.cs
External/Plugins/ProjectManager/Controls/Icons.cs
External/Plugins/ProjectManager/Controls/TreeView/ProjectContextMenu.cs
FlashDevelop/Bin/Debug/Settings/MainMenu.xml
FlashDevelop/Bin/Debug/Settings/ScintillaMenu.xml
FlashDevelop/Bin/Debug/Settings/TabMenu.xml

Add icons to various menus

---

appman.xml

VsThemes updated with additional theme properties.
NavigationBar and QuickLaunch updated to handle ApplyTheme event.

Update builds of community themes and extensions

---

External/Plugins/LoomContext/Projects/LoomProject.cs
External/Plugins/ProjectManager/Controls/PropertiesDialog.cs
External/Plugins/ProjectManager/Controls/TreeView/OtherNodes.cs
External/Plugins/ProjectManager/Projects/AS2/AS2Project.cs
External/Plugins/ProjectManager/Projects/AS3/AS3Project.cs
External/Plugins/ProjectManager/Projects/Generic/GenericProject.cs
External/Plugins/ProjectManager/Projects/Haxe/HaxeProject.cs
External/Plugins/ProjectManager/Projects/Project.cs

Language.ToUpper works for as2 and as3, but looks strange for haxe (HAXE) and loom (LOOM).

Project: add LanguageDisplayName

---

External/Plugins/CodeRefactor/PluginMain.cs

fixes: organize imports from one or more

---

External/Tools/FDBuild/Building/AS3/MxmlcArgumentBuilder.cs

Sdk version 4.11 greater than 4.9, but 4.11(double) less 4.9(double)
(this fix was tested in my project in main work)
ps
sorry ;)

FIX -advanced-telemetry for Apache Flex SDK

---

External/Plugins/ASCompletion/PluginUI.cs

Fix crashes OutlinePanel when use //{ region ... //} endregion

---

External/Plugins/ProjectManager/Controls/NewProjectDialog.cs

[UI NewProjectDialog] Improved display of the path of a new project

---

appman.xml

But i cannot do update for http://www.flashdevelop.org/appman/frameworks_flexsdk_9-18.zip

[Appman] FP19, AIR 19 and update others to the latest versions

---

External/Plugins/ASCompletion/Completion/ASComplete.cs

Fixes add ";" for imports

---

External/Plugins/HaXeContext/Completion/HaxeComplete.cs

Should not escape quotes for --macro statements

---

External/Plugins/ASCompletion/Completion/ASComplete.cs
External/Plugins/ASCompletion/Completion/ASGenerator.cs
External/Plugins/ASCompletion/Model/ASFileParser.cs

Removed some code that has been dead and unreachable for quite some time.

Minor cleanup

---

FlashDevelop/MainForm.cs

If the GoTo, Find/Replace in files and Find/Replace in document dialogs are already open, activate them for better UX.
Also, minor cleanup in MainForm.
This fixes issue #896.

Minor UX improvement

---

CONTRIBUTING.md

There were some duplicate closing brackets. Also, the indent example used a mix of spaces of tabs, which I don't think was intentional?

Contributing.md highlighting and fixes

---

External/Plugins/CodeRefactor/CodeRefactor.csproj
External/Plugins/CodeRefactor/Commands/Rename.cs
External/Plugins/CodeRefactor/PluginMain.cs
External/Plugins/CodeRefactor/Provider/MovingHelper.cs
External/Plugins/CodeRefactor/Provider/RefactoringHelper.cs
External/Plugins/CodeRefactor/Provider/RenamingHelper.cs

closes #237

---

External/Plugins/ProjectManager/Helpers/LineEntryDialog.cs
External/Plugins/ProjectManager/PluginMain.cs
FlashDevelop/Dialogs/ShortcutDialog.cs
FlashDevelop/MainForm.cs
FlashDevelop/Managers/ShortcutManager.cs
PluginCore/PluginCore/Interfaces.cs

Re-done #974, with this time only necessary changes :)  (plus little code refactoring for `ShortcutManager` class).
Provides better mechanism for checking for shortcuts.
More commits are to come, regarding the suggestions from @Neverbirth. I made this PR before those commits as they will be delayed for quite a while (they are pretty much finished however). 
However, the changes made in this commit are not going to be modified, so feel free to review and comment.
~~why is it so easy to make a typo of "shorcut"??? (don't look at my commit message)~~

Improvements on shortcuts mechanism

---

FlashDevelop/Bin/Debug/Library/AS3/intrinsic/FP11/Vector.as

http://help.adobe.com/en_US/FlashPlatform/reference/actionscript/3/Vector.html#insertAt()
http://help.adobe.com/en_US/FlashPlatform/reference/actionscript/3/Vector.html#removeAt()

[Flash] Add support of new API Vector.<T> 

---

External/Plugins/ASCompletion/Completion/ASGenerator.cs

When `ASCompletion` generates variables and functions, and the setting is to generate `protected` access modifier, check for the `FlagType.Final` flag of the current class. If the current class is a `final` class, generate a `private` access modifier instead.
Closes #890.

Don't generate protected members for sealed classes

---

External/Plugins/ASCompletion/Completion/ASGenerator.cs
External/Plugins/ASCompletion/PluginMain.cs
PluginCore/PluginCore/Resources/de_DE.resX
PluginCore/PluginCore/Resources/en_US.resX
PluginCore/PluginCore/Resources/eu_ES.resX
PluginCore/PluginCore/Resources/ja_JP.resX
PluginCore/PluginCore/Resources/zh_CN.resx

Display a message on the status bar when no contextual generation options are available.

Contextual Code Generation update

---

External/Plugins/ProjectManager/Controls/TreeBar.cs
External/Plugins/ProjectManager/PluginMain.cs
External/Plugins/ProjectManager/PluginUI.cs
PluginCore/PluginCore/Resources/de_DE.resX
PluginCore/PluginCore/Resources/en_US.resX
PluginCore/PluginCore/Resources/eu_ES.resX
PluginCore/PluginCore/Resources/ja_JP.resX
PluginCore/PluginCore/Resources/zh_CN.resx

This reverts the PR as discussed [here](https://github.com/fdorg/flashdevelop/pull/639#issuecomment-163182738).
Note, I had to update the basque translation, because before the reverted PR it was using English text.
Opinions are always welcome, the people I've talked to either agree or don't mind this change.

Revert "Merge pull request #639 from Gama11/TrackActiveDocument"

---

External/Plugins/ResultsPanel/PluginMain.cs
External/Plugins/ResultsPanel/PluginUI.cs

Added more options for results panel shortcuts.
Fixed a bug of results panel context menu not updating shortcut key texts.
Closes #940.

More Results Panel Shortcuts

---

FlashDevelop/Bin/Debug/Docs/index.html

Added Microsoft.NET 3.5 requirement to docs.
I also done this in the distro_haxedevelop version.

Minor copy change doc

---

FlashDevelop/Bin/Debug/Tools/appman/Locales/ko_KR.xml
FlashDevelop/FlashDevelop.csproj
FlashDevelop/Resources/SnippetVars.en_US.txt
FlashDevelop/Resources/SnippetVars.ko_KR.txt
PluginCore/PluginCore/Localization/TextHelper.cs
PluginCore/PluginCore/Resources/ko_KR.resX

Korean Locale (2)

---

appman.xml

Seems to be a typo, it's "Advanced" in this thread as well: http://www.flashdevelop.org/community/viewtopic.php?f=4&t=12200

appman.xml: Advance -> Advanced

---

External/Plugins/ProjectManager/Controls/TreeView/OtherNodes.cs
External/Plugins/ProjectManager/Controls/TreeView/ProjectContextMenu.cs
External/Plugins/ProjectManager/PluginMain.cs
External/Plugins/ProjectManager/PluginUI.cs

Rename project from Project Manger

---

Tests/External/Plugins/ASCompletion.Tests/MainForm.cs
Tests/External/Plugins/ASCompletion.Tests/TestUtils/ContextExtensions.cs

Also some leftovers from experimenting. Ooops.

Fixed unit tests after latest changes.

---

External/Plugins/ASCompletion/Model/ASFileParser.cs
Tests/External/Plugins/ASCompletion.Tests/ASCompletion.Tests.csproj
Tests/External/Plugins/ASCompletion.Tests/Model/ASFileParserTests.cs
Tests/External/Plugins/ASCompletion.Tests/Test Files/parser/haxe/ComplexClassTest.hx
Tests/External/Plugins/ASCompletion.Tests/Test Files/parser/haxe/FunctionTypesWithSubTypesTest.hx
Tests/External/Plugins/ASCompletion.Tests/Test Files/parser/haxe/MetadataTest.hx

Generics in function types, and haxe metadata parsing.
Should fix issues #372, #379 and #1065.

Haxe parsing improvements

---

PluginCore/PluginCore/Controls/RichToolTip.cs

Minor layout fix, adjusting paddings to high-dpi.

Tooltip highdpi tweak

---

External/Plugins/ProjectManager/Controls/OpenResourceForm.cs

This is a major annoyance for me, so this tiny improvement would make me very happy.

Making it so that OpenResource panel remembers your last search.

---

appman.xml

also need to create:
http://www.flashdevelop.org/appman/frameworks_flexsdk_9-21.zip

[AppMan] Adds FP21 and AIR21

---

External/Plugins/CodeRefactor/Commands/Rename.cs
External/Plugins/CodeRefactor/PluginMain.cs
External/Plugins/CodeRefactor/Provider/RenamingHelper.cs

I will try to do PR with unit tests soon.

[Critical] Fixes a bug which does not allow to rename the package

---

External/Plugins/CodeRefactor/Controls/MoveDialog.Designer.cs
External/Plugins/CodeRefactor/Controls/MoveDialog.cs
External/Plugins/CodeRefactor/PluginMain.cs

Result:
If you set a hotkey "RefactorMenu.Move" it will work in the project panel.

Adds item "Move" to context menu of Project Manager

---

External/Plugins/ASCompletion/Completion/ASGenerator.cs
FlashDevelop/Bin/Debug/Snippets/as2/generators/EventHandler.fds
FlashDevelop/Bin/Debug/Snippets/as3/generators/EventHandler.fds
FlashDevelop/Bin/Debug/Snippets/haxe/generators/EventHandler.fds
Tests/External/Plugins/ASCompletion.Tests/Completion/ASGeneratorTests.cs

eg. DOM addEventListener shouldn't import flash.events.Event or even suggest to generate a DataEvent handler.

Better events generator when using Haxe not for Flash. 

---

CONTRIBUTING.md

CONTRIBUTING.md: C# doesn't have "import"

---

External/Plugins/FileExplorer/PluginMain.cs
External/Plugins/ProjectManager/PluginMain.cs
FlashDevelop/FlashDevelop.csproj
FlashDevelop/MainForm.cs
FlashDevelop/Settings/Accessors.cs
FlashDevelop/Settings/Properties.cs
PluginCore/PluginCore/Interfaces.cs
PluginCore/PluginCore/Resources/de_DE.resX
PluginCore/PluginCore/Resources/en_US.resX
PluginCore/PluginCore/Resources/eu_ES.resX
PluginCore/PluginCore/Resources/ja_JP.resX
PluginCore/PluginCore/Resources/ko_KR.resX
PluginCore/PluginCore/Resources/zh_CN.resx
Tests/External/Plugins/ASCompletion.Tests/MainForm.cs

Falls back to cmd.exe if it's not a valid file.
This allows changing the hardcoded cmd.exe to whatever command prompt you like (cmder.exe, Git bash, PowerShell...)

Add a "Custom Command Prompt" setting

---

External/Plugins/ASCompletion/Completion/ASComplete.cs

Incorrect FindParameterIndex reference position when using compiler completion

---

External/Plugins/ProjectManager/Controls/FDMenus.cs
FlashDevelop/Bin/Debug/Settings/Themes/Default.fdi
FlashDevelop/Bin/Debug/Settings/Themes/DimGray.fdi
FlashDevelop/Bin/Debug/Settings/Themes/Obsidian.fdi
FlashDevelop/Bin/Debug/Settings/Themes/Thyleus.fdi

Made target selector a bit larger by default, and now both drop downs have a configurable size.

Toolbar dropdown size

---

External/Plugins/AirProperties/Forms/LocaleManager.cs
External/Plugins/AirProperties/Managers/PropertyManager.cs
External/Plugins/AirProperties/PluginMain.cs
FlashDevelop/Bin/Debug/Settings/Platforms/AS3/air.xml
FlashDevelop/Bin/Debug/Settings/Platforms/AS3/airmobile.xml
FlashDevelop/Bin/Debug/Settings/Platforms/AS3/flashplayer.xml
FlashDevelop/Bin/Debug/Settings/Platforms/Haxe/air.xml
FlashDevelop/Bin/Debug/Settings/Platforms/Haxe/airmobile.xml
FlashDevelop/Bin/Debug/Settings/Platforms/Haxe/flashplayer.xml

Basic support of AIR 22

---

appman.xml

Small update to solarized theme

Appman solarized theme v1.1.1

---

FlashDevelop/Managers/ButtonManager.cs
FlashDevelop/Settings/Accessors.cs
FlashDevelop/Settings/Properties.cs
PluginCore/PluginCore/Resources/de_DE.resX
PluginCore/PluginCore/Resources/en_US.resX
PluginCore/PluginCore/Resources/eu_ES.resX
PluginCore/PluginCore/Resources/ja_JP.resX
PluginCore/PluginCore/Resources/ko_KR.resX
PluginCore/PluginCore/Resources/zh_CN.resx

Resolves #1255 
Details: http://www.flashdevelop.org/community/viewtopic.php?f=13&t=12645

Add settings for max recent files

---

FlashDevelop/Controls/FilteredGrid.cs
FlashDevelop/Dialogs/SettingDialog.cs
FlashDevelop/Settings/Properties.cs

This is not the best solution, as it doesn't ensure the first _category_ to be visible, which is visually the first row before the first item.

Select first entry in settings dialog.

---

appman.xml

This is what happens if I try to edit comments inside XML... :(

XML Ampersand Problem

---

PluginCore/PluginCore/Helpers/FileHelper.cs

Closes #1166 
Currently 10/13 PR's are mine lol.

Fixes error on save for hidden files.

---

FlashDevelop/Dialogs/SettingDialog.cs
FlashDevelop/Dialogs/ShortcutDialog.cs
FlashDevelop/MainForm.cs

Save configurations on dialog close

---

PluginCore/PluginCore/Resources/de_DE.resX
PluginCore/PluginCore/Resources/en_US.resX
PluginCore/PluginCore/Resources/eu_ES.resX
PluginCore/PluginCore/Resources/ja_JP.resX
PluginCore/PluginCore/Resources/ko_KR.resX
PluginCore/PluginCore/Resources/zh_CN.resx

Resource string updates

---

FlashDevelop/MainForm.cs

Closes #856 
11 out of 14 now :)

Restore FD position regarding multiple monitors.

---

FlashDevelop/Managers/ScintillaManager.cs
FlashDevelop/Settings/Accessors.cs

http://www.flashdevelop.org/community/viewtopic.php?f=5&t=12589
Setting `ScrollWidth` to `0` should enable `ScrollWidthTracking` too.

Scroll width tracking

---

PluginCore/PluginCore/Controls/UITools.cs

Do not close snippet on backward selection.

---

External/Plugins/ProjectManager/Actions/ProjectActions.cs
External/Plugins/ProjectManager/Controls/NewProjectDialog.cs
External/Tools/FDBuild/Building/AS2/AS2ProjectBuilder.cs
External/Tools/FDBuild/FDBuild.csproj
External/Tools/FDBuild/Program.cs
FlashDevelop/Controls/QuickFind.cs
FlashDevelop/Dialogs/SettingDialog.cs
FlashDevelop/MainForm.cs
PluginCore/DockPanelSuite/Customization/DockPanelStripRenderer.cs
PluginCore/PluginCore.csproj
PluginCore/PluginCore/Helpers/JvmConfigHelper.cs
PluginCore/PluginCore/Helpers/PathHelper.cs
PluginCore/PluginCore/Helpers/PlatformHelper.cs
PluginCore/PluginCore/Win32.cs

Fixes .as2proj / .as3proj projects build in Linux. Works in Windows as well.

[FDBuild] fix project building in Linux.

---

External/Plugins/ASCompletion/Completion/ArgumentsProcessor.cs

Contributed [here](http://flashdevelop.org/community/viewtopic.php?p=55068#p55068).

Make argument detection culture invariant.

---

External/Plugins/AirProperties/Forms/AirWizard.cs
External/Plugins/AirProperties/Managers/PropertyManager.cs
FlashDevelop/Bin/Debug/Settings/Platforms/AS3/air.xml
FlashDevelop/Bin/Debug/Settings/Platforms/AS3/airmobile.xml
FlashDevelop/Bin/Debug/Settings/Platforms/AS3/flashplayer.xml
FlashDevelop/Bin/Debug/Settings/Platforms/Haxe/air.xml
FlashDevelop/Bin/Debug/Settings/Platforms/Haxe/airmobile.xml
FlashDevelop/Bin/Debug/Settings/Platforms/Haxe/flashplayer.xml

AIR 23 Beta Release notes: http://fpdownload.macromedia.com/pub/labs/flashruntimes/shared/air23_flashplayer23_releasenotes.pdf

Support of AIR 23

---

External/Plugins/ASCompletion/Completion/ASGenerator.cs

[Haxe] Fixed contextual generator for  `var some(get, set)`

---

External/Plugins/ProjectManager/Controls/TreeView/OtherNodes.cs
PluginCore/PluginCore/Helpers/DrawHelper.cs

Just avoid some unneeded exceptions.

Avoid some unneeded exceptions.

---

External/Plugins/ASCompletion/Completion/ASGenerator.cs
FlashDevelop/Bin/Debug/Snippets/haxe/generators/OverrideSetter.fds
Tests/External/Plugins/ASCompletion.Tests/ASCompletion.Tests.csproj
Tests/External/Plugins/ASCompletion.Tests/Completion/ASGeneratorTests.cs
Tests/External/Plugins/ASCompletion.Tests/Test Files/generated/haxe/AfterOverrideIssue793.hx
Tests/External/Plugins/ASCompletion.Tests/Test Files/generated/haxe/BeforeOverrideIssue793.hx

Fixed autoimport after property overrides. Fixes #793

---

Tests/External/Plugins/ASCompletion.Tests/MainForm.cs
Tests/External/Plugins/CodeRefactor.Tests/MainForm.cs

Change some code that seems to be invalid. It doesn't give errors from VS and the CI server, but does from command line.
The reason for it to be apparently invalid is because the read only property is never initialized to a value.

Changed some test code

---

CI/build.cmd
Tests/External/Plugins/ASCompletion.Tests/MainForm.cs
Tests/External/Plugins/CodeRefactor.Tests/MainForm.cs

Improvements for local and CI build:
- No need for rebuilding the whole project for the AnyCPU build.
- Only run tests if we are in the CI server.
- Make a package for PRs for easier testing and experimenting from everyone.

Test improvements

---

CI/tests.ps1
Tests/External/Plugins/CodeRefactor.Tests/Commands/CodeRefactorTests.cs

No need to overcomplicate things...

Fixed list of assemblies passed to NUnit (II)

---

External/Plugins/ASCompletion/Completion/ASGenerator.cs
Tests/External/Plugins/ASCompletion.Tests/ASCompletion.Tests.csproj
Tests/External/Plugins/ASCompletion.Tests/Completion/ASGeneratorTests.cs
Tests/External/Plugins/ASCompletion.Tests/Test Files/generated/haxe/AfterAssignStatementToVar_useSpaces.hx
Tests/External/Plugins/ASCompletion.Tests/Test Files/generated/haxe/AfterAssignStatementToVar_useTabs.hx
Tests/External/Plugins/ASCompletion.Tests/Test Files/generated/haxe/BeforeAssignStatementToVar_useSpaces.hx
Tests/External/Plugins/ASCompletion.Tests/Test Files/generated/haxe/BeforeAssignStatementToVar_useTabs.hx

Fixed formatting of "Assign statement to variable"

---

CI/deploy.ps1

Which kind of extra info would be helpful? build date for the PR in case it gets multiple commits?

Take PR builds into account for deployment.

---

FlashDevelop.sln
Tests/PluginCore/PluginCore.Tests/PluginCore.Tests.csproj
Tests/PluginCore/PluginCore.Tests/app.config
Tests/PluginCore/PluginCore.Tests/packages.config

Why wasn't this caught in the corresponding PR? will have to investigate, although I have some ideas and it may not be important.

Build configuration and new tests fixes.

---

External/Plugins/ASCompletion/Completion/ASComplete.cs

Use LineEndDetector when getting CodeTip text.

---

External/Plugins/ASClassWizard/PluginMain.cs

Fix ASClassWizard interface implementation with multiple interfaces

---

External/Plugins/ASCompletion/Completion/ASComplete.cs
External/Plugins/ASCompletion/PluginMain.cs
External/Plugins/CodeRefactor/PluginMain.cs
PluginCore/PluginCore/Resources/de_DE.resX
PluginCore/PluginCore/Resources/en_US.resX
PluginCore/PluginCore/Resources/eu_ES.resX
PluginCore/PluginCore/Resources/ja_JP.resX
PluginCore/PluginCore/Resources/ko_KR.resX
PluginCore/PluginCore/Resources/zh_CN.resx

Adds `Goto Type Declaration`

---

External/Plugins/AirProperties/Managers/PropertyManager.cs
FlashDevelop/Bin/Debug/Settings/Platforms/AS3/air.xml
FlashDevelop/Bin/Debug/Settings/Platforms/AS3/airmobile.xml
FlashDevelop/Bin/Debug/Settings/Platforms/AS3/flashplayer.xml
appman.xml

@Meychi please update http://www.flashdevelop.org/appman/frameworks_flexsdk_9-22.zip to 24 version

Support of AIR 24 and FlashPlayer 24. closes issue #1418

---

External/Plugins/ASCompletion/Completion/ASComplete.cs
External/Plugins/CodeRefactor/Provider/RefactoringHelper.cs
Tests/External/Plugins/ASCompletion.Tests/ASCompletion.Tests.csproj
Tests/External/Plugins/ASCompletion.Tests/Completion/ASCompleteTests.cs
Tests/External/Plugins/ASCompletion.Tests/Test Files/completion/as3/GetExpressionTypeOfConstructor.as
Tests/External/Plugins/ASCompletion.Tests/Test Files/completion/as3/GetExpressionTypeOfConstructorParameter.as
Tests/External/Plugins/ASCompletion.Tests/Test Files/completion/as3/GetExpressionTypeOfFunction.as
Tests/External/Plugins/ASCompletion.Tests/Test Files/completion/as3/GetExpressionTypeOfFunctionParameter.as
Tests/External/Plugins/ASCompletion.Tests/Test Files/completion/as3/GetExpressionTypeOfFunctionParameter2.as
Tests/External/Plugins/ASCompletion.Tests/Test Files/completion/as3/GetExpressionTypeOfFunctionWithParameter.as
Tests/External/Plugins/ASCompletion.Tests/Test Files/completion/as3/GetExpressionTypeOfLocalObjectKey.as
Tests/External/Plugins/ASCompletion.Tests/Test Files/completion/as3/GetExpressionTypeOfLocalObjectValue.as
Tests/External/Plugins/ASCompletion.Tests/Test Files/completion/as3/GetExpressionTypeOfLocalVar.as
Tests/External/Plugins/ASCompletion.Tests/Test Files/completion/as3/GetExpressionTypeOfSetterParameter.as
Tests/External/Plugins/ASCompletion.Tests/Test Files/completion/as3/GetExpressionTypeOfVariable.as
Tests/External/Plugins/ASCompletion.Tests/Test Files/completion/haxe/GetExpressionTypeOfConstructor.hx
Tests/External/Plugins/ASCompletion.Tests/Test Files/completion/haxe/GetExpressionTypeOfConstructorParameter.hx
Tests/External/Plugins/ASCompletion.Tests/Test Files/completion/haxe/GetExpressionTypeOfFunction.hx
Tests/External/Plugins/ASCompletion.Tests/Test Files/completion/haxe/GetExpressionTypeOfFunctionParameter.hx
Tests/External/Plugins/ASCompletion.Tests/Test Files/completion/haxe/GetExpressionTypeOfFunctionParameter2.hx
Tests/External/Plugins/ASCompletion.Tests/Test Files/completion/haxe/GetExpressionTypeOfFunctionWithParameter.hx
Tests/External/Plugins/ASCompletion.Tests/Test Files/completion/haxe/GetExpressionTypeOfLocalDynamicKey.hx
Tests/External/Plugins/ASCompletion.Tests/Test Files/completion/haxe/GetExpressionTypeOfLocalDynamicValue.hx
Tests/External/Plugins/ASCompletion.Tests/Test Files/completion/haxe/GetExpressionTypeOfLocalVar.hx
Tests/External/Plugins/ASCompletion.Tests/Test Files/completion/haxe/GetExpressionTypeOfPropertyGetter.hx
Tests/External/Plugins/ASCompletion.Tests/Test Files/completion/haxe/GetExpressionTypeOfPropertySetter.hx
Tests/External/Plugins/ASCompletion.Tests/Test Files/completion/haxe/GetExpressionTypeOfVariable.hx

@elsassph @Neverbirth please review this PR

Fixes #1370

---

External/Plugins/CodeRefactor/CodeRefactor.csproj
External/Plugins/CodeRefactor/Provider/CommandFactory.cs
External/Plugins/CodeRefactor/Provider/CommandFactoryProvider.cs
External/Plugins/CodeRefactor/Provider/UserInterfaceManager.cs
External/Plugins/HaXeContext/CodeRefactor/Commands/HaxeFindAllReferences.cs
External/Plugins/HaXeContext/CodeRefactor/Provider/HaxeCommandFactory.cs
External/Plugins/HaXeContext/Completion/HaxeComplete.cs
External/Plugins/HaXeContext/Context.cs
External/Plugins/HaXeContext/HaXeContext.csproj
External/Plugins/HaXeContext/PluginMain.cs

Result: ![haxe_rename_local_var](https://cloud.githubusercontent.com/assets/1700940/22330044/42520aa6-e3d5-11e6-8100-022d35c0d705.gif)
@Neverbirth @elsassph please review this PR

Improved rename local variables for Haxe

---

External/Plugins/OutputPanel/PluginUI.cs

- Fix resizing in panel. Fully fixes #1148.
- Do not enable scrollTimer by default, unneeded and sometimes when debugging could throw cross thread exceptions.
- Fix panel visibility when autoscroll was disabled. It was making wrong and unneeded operations.
I never realized how buggy the RichTextBox resizing/scrolling logic was... even using the latest RichEdit control that was released in Windows XP (newer than the one used in .NET) shows this problem. I don't know if it's some kind of hidden setting. The most obvious problem (but there are others, like the fixed problem): when you have the caret at the bottom of the control, while having a scrollbar, resize the control, the scrollbar will resize, and the text will move upwards leaving a lot of blank space below, when doing something the …

Improve OutputPanel

---

External/Plugins/ASCompletion/Completion/ASGenerator.cs
PluginCore/PluginCore/Helpers/PathHelper.cs
Tests/External/Plugins/ASCompletion.Tests/ASCompletion.Tests.csproj
Tests/External/Plugins/ASCompletion.Tests/Completion/ASGeneratorTests.cs
Tests/External/Plugins/ASCompletion.Tests/Test Files/generated/as3/AfterAssignStatementToVarFromMethodChaining2_useSpaces.as
Tests/External/Plugins/ASCompletion.Tests/Test Files/generated/as3/AfterAssignStatementToVarFromMethodChaining_useSpaces.as
Tests/External/Plugins/ASCompletion.Tests/Test Files/generated/as3/AfterAssignStatementToVarFromMultilineArrayInitializer_useSpaces.as
Tests/External/Plugins/ASCompletion.Tests/Test Files/generated/as3/AfterAssignStatementToVarFromMultilineObjectInitializer2_useSpaces.as
Tests/External/Plugins/ASCompletion.Tests/Test Files/generated/as3/AfterAssignStatementToVarFromMultilineObjectInitializer_useSpaces.as
Tests/External/Plugins/ASCompletion.Tests/Test Files/generated/as3/BeforeAssignStatementToVarFromMethodChaining2_useSpaces.as
Tests/External/Plugins/ASCompletion.Tests/Test Files/generated/as3/BeforeAssignStatementToVarFromMethodChaining_useSpaces.as
Tests/External/Plugins/ASCompletion.Tests/Test Files/generated/as3/BeforeAssignStatementToVarFromMultilineArrayInitializer_useSpaces.as
Tests/External/Plugins/ASCompletion.Tests/Test Files/generated/as3/BeforeAssignStatementToVarFromMultilineObjectInitializer2_useSpaces.as
Tests/External/Plugins/ASCompletion.Tests/Test Files/generated/as3/BeforeAssignStatementToVarFromMultilineObjectInitializer_useSpaces.as

@Neverbirth @elsassph please review this PR

Assign multiline statement to local var

---

External/Plugins/ProjectManager/Actions/ProjectActions.cs
External/Plugins/ProjectManager/PluginMain.cs
External/Plugins/ProjectManager/PluginUI.cs
PluginCore/PluginCore/Helpers/FileInspector.cs
PluginCore/PluginCore/Resources/de_DE.resX
PluginCore/PluginCore/Resources/en_US.resX
PluginCore/PluginCore/Resources/eu_ES.resX
PluginCore/PluginCore/Resources/ja_JP.resX
PluginCore/PluginCore/Resources/ko_KR.resX
PluginCore/PluginCore/Resources/zh_CN.resx

Import a Haxe hxml Project

---

.gitignore
FlashDevelop/Properties/AssemblyInfo.cs.rev
PluginCore/ScintillaNet/ScintillaControl.cs
Tests/PluginCore/PluginCore.Tests/MainForm.cs
Tests/PluginCore/PluginCore.Tests/PluginCore.Tests.csproj
Tests/PluginCore/PluginCore.Tests/ScintillaNet/ScintillaControlTests.cs
Tests/PluginCore/PluginCore.Tests/packages.config

@Neverbirth please review this PR

Added method `ScintillaControl.getWordRight` + Tests

---

External/Plugins/ASCompletion/Completion/ASComplete.cs

I'll add tests after the merger #1458

Fixes issue #1387

---

appman.xml

Guys please create http://www.flashdevelop.org/appman/frameworks_flexsdk_9-25.zip
http://www.adobe.com/support/flashplayer/debug_downloads.html

[AppMan] Update FlashPlayer and AIR to version 25

---

PluginCore/PluginCore/Controls/FixedValuesCollectionEditor.cs

Fixes FixedValuesCollectionEditor creating ellipses

---

External/Plugins/AS2Context/Context.cs
External/Plugins/ASCompletion/Completion/ASComplete.cs
External/Plugins/ASCompletion/Model/MemberModel.cs
External/Plugins/ASCompletion/Model/PathModel.cs
External/Plugins/CodeRefactor/Commands/FindAllReferences.cs
External/Plugins/CodeRefactor/Provider/DocumentHelper.cs
External/Plugins/CodeRefactor/Provider/RefactoringHelper.cs

dotTrace log before fix:
dotTrace log after fix:

[CodeRefactor] Improving performance for "Find All References" command

---

External/Plugins/CodeRefactor/Managers/BatchProcessManager.cs

Make IBatchProcessor removable

---

External/Plugins/CodeRefactor/Controls/RefactorMenu.cs

Plus just some minor code cleanup.

Add Images for Organise & Truncate Imports refactor menu

---

External/Plugins/LintingHelper/BatchProcess/LintProcessor.cs
External/Plugins/LintingHelper/Helpers/DictionaryHelper.cs
External/Plugins/LintingHelper/ILintProvider.cs
External/Plugins/LintingHelper/LintingCache.cs
External/Plugins/LintingHelper/LintingHelper.csproj
External/Plugins/LintingHelper/LintingResult.cs
External/Plugins/LintingHelper/Managers/LintingManager.cs
External/Plugins/LintingHelper/PluginMain.cs
External/Plugins/LintingHelper/Properties/AssemblyInfo.cs
External/Plugins/LintingHelper/Settings.cs
FlashDevelop.sln
PluginCore/PluginCore/Resources/de_DE.resX
PluginCore/PluginCore/Resources/en_US.resX
PluginCore/PluginCore/Resources/eu_ES.resX
PluginCore/PluginCore/Resources/ja_JP.resX
PluginCore/PluginCore/Resources/ko_KR.resX
PluginCore/PluginCore/Resources/zh_CN.resx

The idea is to have one manager to handle linting / code analysis.
I would like to get some comments on this.
It would be worth considering if this belongs into CodeRefactor plugin, for example.
Other than that, what about the overall architecture?
An example for a plugin using it: https://github.com/DoclerLabs/hexDevelop/tree/haxecheckstyle/Plugins/HaxeCheckStyle

Add LintingManager

---

External/Plugins/HaXeContext/Completion/HaxeComplete.cs
External/Plugins/LintingHelper/PluginMain.cs
FlashDevelop/Docking/TabbedDocument.cs
FlashDevelop/MainForm.cs
PluginCore/PluginCore/EventTypes.cs
PluginCore/PluginCore/Interfaces.cs

Add argument to Save

---

External/Plugins/HaXeContext/Linters/DiagnosticsLinter.cs

```
Unhandled exception:
System.Exception: System.NullReferenceException: Object reference not set to an instance of an object.
at HaXeContext.Linters.DiagnosticsLinter.<>c__DisplayClass1_1.<LintAsync>b__0(HaxeComplete complete, List`1 results, HaxeCompleteStatus status)
at HaXeContext.HaxeComplete.Notify[T](HaxeCompleteResultHandler`1 callback, T result)
at HaXeContext.HaxeComplete.<>c__DisplayClass22_0`1.<StartThread>b__0(Object _)
at System.Threading._ThreadPoolWaitCallback.WaitCallback_Context(Object state)
at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
at System.Threading._ThreadPoolWaitCallback.PerformWaitCallbackInternal(_ThreadPoolWaitCallback tpWaitCallBack)
at …
```

[Haxe] Fixed System.NullReferenceException: 'Object reference not set to an instance of an object.'

---

PluginCore/ScintillaNet/ScintillaControl.cs

Closes #489
Doesn't solve the second issue in the comments of the referenced issue.

Closing brace inside strings should not unindent

---

External/Plugins/ASCompletion/Controls/AddClosingBracesRulesEditorForm.cs

Fixed unnecessary event invocations, multiple selected index changes in one operation, etc.

Small updates to AddClosingBracesRulesEditorForm

---

FlashDevelop/Dialogs/SettingDialog.cs

Remove useless scroll bar in SettingDialog

---

PluginCore/PluginCore/Controls/FixedValuesCollectionEditor.cs

Modified `AutoScaleDimensions` to 8x20 and updated location&size of controls.

FixedValuesCollectionEditor AutoScale changes

---

.gitignore

Ignore test output files

---

Tests/External/Plugins/ASCompletion.Tests/Completion/ASCompleteTests.cs
Tests/External/Plugins/ASCompletion.Tests/Completion/ASGeneratorTests.cs

Speed up tests

---

External/Plugins/ASCompletion/Completion/ASComplete.cs
External/Plugins/ASCompletion/Completion/ASGenerator.cs
Tests/External/Plugins/ASCompletion.Tests/ASCompletion.Tests.csproj
Tests/External/Plugins/ASCompletion.Tests/Completion/ASGeneratorTests.cs
Tests/External/Plugins/ASCompletion.Tests/Test Files/generated/haxe/AfterAssignStatementToVarFromCastExp.hx
Tests/External/Plugins/ASCompletion.Tests/Test Files/generated/haxe/BeforeAssignStatementToVarFromCastExp.hx

@Neverbirth please review this PR

[Haxe][ASGenerator] Fixed of assign statement to variable from cast expression

---

FlashDevelop/Bin/Debug/Settings/MainMenu.xml
FlashDevelop/Dialogs/ClipboardHistoryDialog.cs
FlashDevelop/FlashDevelop.csproj
FlashDevelop/MainForm.cs
FlashDevelop/Managers/ClipboardManager.cs
FlashDevelop/Settings/Accessors.cs
FlashDevelop/Settings/Properties.cs
PluginCore/PluginCore.csproj
PluginCore/PluginCore/Collections/FixedSizeQueue.cs
PluginCore/PluginCore/Interfaces.cs
PluginCore/PluginCore/Managers/ClipboardManager.cs
PluginCore/PluginCore/Resources/de_DE.resx
PluginCore/PluginCore/Resources/en_US.resx
PluginCore/PluginCore/Resources/eu_ES.resx
PluginCore/PluginCore/Resources/ja_JP.resx
PluginCore/PluginCore/Resources/ko_KR.resx
PluginCore/PluginCore/Resources/zh_CN.resx

Clipboard History

---

External/Plugins/AirProperties/Managers/PropertyManager.cs
FlashDevelop/Bin/Debug/Projects/160 ActionScript 3 - AIR AS3 Projector/Project.as3proj
FlashDevelop/Bin/Debug/Projects/160 ActionScript 3 - AIR AS3 Projector/application.xml.template
FlashDevelop/Bin/Debug/Projects/180 ActionScript 3 - AIR Flex 4 Projector/Project.as3proj
FlashDevelop/Bin/Debug/Projects/180 ActionScript 3 - AIR Flex 4 Projector/application.xml.template
FlashDevelop/Bin/Debug/Projects/190 ActionScript 3 - AIR Mobile AS3 App/Project.as3proj
FlashDevelop/Bin/Debug/Projects/190 ActionScript 3 - AIR Mobile AS3 App/application.xml.template
FlashDevelop/Bin/Debug/Projects/195 ActionScript 3 - AIR Mobile Flex App/Project.as3proj
FlashDevelop/Bin/Debug/Projects/195 ActionScript 3 - AIR Mobile Flex App/application.xml.template
FlashDevelop/Bin/Debug/Projects/315 Haxe - AIR Projector/application.xml.template
FlashDevelop/Bin/Debug/Settings/Platforms/AS3/air.xml
FlashDevelop/Bin/Debug/Settings/Platforms/AS3/airmobile.xml
FlashDevelop/Bin/Debug/Settings/Platforms/AS3/flashplayer.xml

For users who use AIR and FP from http://labs.adobe.com/
http://fpdownload.macromedia.com/pub/labs/flashruntimes/shared/air26_flashplayer26_releasenotes.pdf

Basic support of AIR26 and FP26

---

External/Plugins/HaXeContext/PluginMain.cs

```
Parameter name: input
at System.Text.RegularExpressions.Regex.Match(String input)
at HaXeContext.PluginMain.HandleEvent(Object sender, NotifyEvent e, HandlingPriority priority)
at PluginCore.Managers.EventManager.DispatchEvent(Object sender, NotifyEvent e)
```

Fixed ArgumentNullException

---

FlashDevelop/Settings/Accessors.cs

Fix "The FixedSizeQueue has zero capacity" Error

---

FlashDevelop/Dialogs/FRInDocDialog.cs
FlashDevelop/Dialogs/FRInFilesDialog.cs

FindAndReplace dialogs should retain focus after regex error dialog

---

FlashDevelop/Controls/QuickFind.cs

Do not trim search string in QuickFind

---

External/Plugins/ResultsPanel/PluginUI.cs

ResultsPanel double click also selects the entry

---

External/Plugins/CodeRefactor/Provider/RefactoringHelper.cs
External/Plugins/HaXeContext/CodeRefactor/Provider/HaxeCommandFactory.cs
External/Plugins/HaXeContext/Completion/HaxeComplete.cs
External/Plugins/HaXeContext/Context.cs
External/Plugins/HaXeContext/Linters/DiagnosticsLinter.cs
PluginCore/PluginCore/Utilities/SemVer.cs
Tests/PluginCore/PluginCore.Tests/PluginCore/Utilities/SemVerTests.cs

Comparison operators for SemVer

---

FlashDevelop/MainForm.cs

https://github.com/fdorg/flashdevelop/pull/1649#issuecomment-310198104

Fix first run stacking panels on the right

---

External/Plugins/AS2Context/Properties/AssemblyInfo.cs
External/Plugins/AS3Context/Properties/AssemblyInfo.cs
External/Plugins/ASClassWizard/Properties/AssemblyInfo.cs
External/Plugins/ASCompletion/Properties/AssemblyInfo.cs
External/Plugins/BasicCompletion/Properties/AssemblyInfo.cs
External/Plugins/BookmarkPanel/Properties/AssemblyInfo.cs
External/Plugins/BridgeSettings/Properties/AssemblyInfo.cs
External/Plugins/CodeAnalyzer/Properties/AssemblyInfo.cs
External/Plugins/CodeFormatter/Properties/AssemblyInfo.cs
External/Plugins/CodeRefactor/Properties/AssemblyInfo.cs
External/Plugins/DataEncoder/Properties/AssemblyInfo.cs
External/Plugins/FileExplorer/Properties/AssemblyInfo.cs
External/Plugins/FlashConnect/Properties/AssemblyInfo.cs
External/Plugins/FlashDebugger/Properties/AssemblyInfo.cs
External/Plugins/FlashLogViewer/Properties/AssemblyInfo.cs
External/Plugins/FlashViewer/Properties/AssemblyInfo.cs
External/Plugins/HaXeContext/Properties/AssemblyInfo.cs
External/Plugins/LayoutManager/Properties/AssemblyInfo.cs
External/Plugins/LintingHelper/Properties/AssemblyInfo.cs
External/Plugins/MacroManager/Properties/AssemblyInfo.cs
External/Plugins/OutputPanel/Properties/AssemblyInfo.cs
External/Plugins/PHPContext/Properties/AssemblyInfo.cs
External/Plugins/ResultsPanel/Properties/AssemblyInfo.cs
External/Plugins/StartPage/Properties/AssemblyInfo.cs
External/Plugins/TaskListPanel/Properties/AssemblyInfo.cs
PluginCore/Properties/AssemblyInfo.cs
Tests/External/Plugins/ASCompletion.Tests/Properties/AssemblyInfo.cs
Tests/External/Plugins/CodeRefactor.Tests/Properties/AssemblyInfo.cs
Tests/PluginCore/PluginCore.Tests/Properties/AssemblyInfo.cs

These changes wouldn't cause any problems, would they?

AssemblyInfo consistency

---

FlashDevelop/Managers/LayoutManager.cs

`EventType.RestoreSession` will no longer be dispatched when changing layout, but I don't see why session needs to be "restored" during layout changes anyway.
@Meychi 
Closes #1014

Prevent documents from closing during layout changes

---

PluginCore/ScintillaNet/ScintillaControl.cs

Just in case the anchor position causes any problems.

Update anchor position

---

External/Plugins/AirProperties/Managers/PropertyManager.cs
FlashDevelop/Bin/Debug/Settings/Platforms/AS3/air.xml
FlashDevelop/Bin/Debug/Settings/Platforms/AS3/airmobile.xml
FlashDevelop/Bin/Debug/Settings/Platforms/AS3/flashplayer.xml

Release notes: http://fpdownload.macromedia.com/pub/labs/flashruntimes/shared/air27_flashplayer27_releasenotes.pdf

Basic support of AIR27 and FP27

---

PluginCore/Properties/AssemblyInfo.cs
PluginCore/ScintillaNet/ScintillaControl.cs
Tests/PluginCore/PluginCore.Tests/ScintillaNet/ScintillaControlTests.cs

Fixes #1685.
I added a couple of unit tests, it would be nice to see them extended with more cases in the future.

Fixed regression that happened after some "Add closing braces" work

---

FlashDevelop/MainForm.cs
FlashDevelop/Managers/ScintillaManager.cs

Looks like I forgot to change that in the implementors / overriders PR

Fix #1724 by checking for new FoldingMargin index

---

External/Plugins/CodeRefactor/Provider/RefactoringHelper.cs
External/Plugins/SourceControl/Sources/Git/CommitCommand.cs

[SourceControl][Git] Fix fatal pathspec: "New Folder" did not match any files

---

Tests/External/Plugins/CodeRefactor.Tests/CodeRefactor.Tests.csproj
Tests/External/Plugins/CodeRefactor.Tests/Provider/RefactoringHelperTests.cs
Tests/External/Plugins/CodeRefactor.Tests/Test Files/coderefactor/findallreferences/haxe/LocalVar_enum.hx

@Neverbirth please review this PR and merge if all ok

[CodeRefactor][UnitTests] Add simple test for #1825

---

External/Plugins/ASCompletion/PluginMain.cs

Fix implements arrow getting messed up when settings are closed

---

PluginCore/PluginCore/Managers/EventManager.cs

This fixes some of the crashes people may be having.
Performance in single-threaded scenarios will be most times the same and at worst just some nanoseconds slower.

Thread-safe EventManager.

---

FlashDevelop/Managers/ScintillaManager.cs
Tests/External/Plugins/CodeRefactor.Tests/CodeRefactor.Tests.csproj
Tests/External/Plugins/CodeRefactor.Tests/Commands/RefactorCommandTests.cs
Tests/External/Plugins/CodeRefactor.Tests/MainForm.cs
Tests/External/Plugins/CodeRefactor.Tests/Test Files/coderefactor/rename/as3/AfterRenameLocalVariable.as
Tests/External/Plugins/CodeRefactor.Tests/Test Files/coderefactor/rename/as3/BeforeRenameLocalVariable.as

@Neverbirth please review this PR

[UnitTests][CodeRefactor] Simple unit test for Rename command

---

CI/build.cmd
External/Plugins/ASCompletion/PluginMain.cs
External/Plugins/HaXeContext/Completion/CompilerCompletionHandler.cs
External/Plugins/HaXeContext/Context.cs
Tests/External/Plugins/CodeRefactor.Tests/Commands/RefactorCommandTests.cs

Revert "Merge pull request #1838 from chipshort/issues/1815-implement…  …
Better disposing of Haxe processes.
Ignore refactor rename tests until they are fixed...
Fix CI/build.cmd verification of build/test errors

Minor changes

---

External/Plugins/ASCompletion/Completion/ASComplete.cs

[ASComplete] Fixed Class-level autocomplete when writing default values in 'new'. fixes #1887

---

External/Plugins/ASCompletion/Completion/ASComplete.cs

Now 'import completion', 'declaration completion' and 'override completion' disabled within method.

[ASComplete] Fixed autocompletion after space within method. #fixes 1888

---

External/Plugins/ASCompletion/Model/ASFileParser.cs
Tests/External/Plugins/ASCompletion.Tests/ASCompletion.Tests.csproj
Tests/External/Plugins/ASCompletion.Tests/Model/ASFileParserTests.cs
Tests/External/Plugins/ASCompletion.Tests/Test Files/parser/haxe/Issue1964_package_test.extern.hx
Tests/External/Plugins/HaxeContext.Tests/Completion/CodeGeneratorTests.cs
Tests/External/Plugins/HaxeContext.Tests/HaxeContext.Tests.csproj
Tests/External/Plugins/HaxeContext.Tests/Test Files/completion/generated/AfterContextualGeneratorTests_issue1964_1.hx
Tests/External/Plugins/HaxeContext.Tests/Test Files/completion/generated/BeforeContextualGeneratorTests_issue1964_1.hx

https://github.com/HaxeFoundation/HaxeManual/issues/319

[Haxe][ASFileParser] Fixed parsing of files that package of which contains 'extern' keyword. fixes #1964

---

External/Plugins/CodeRefactor/PluginMain.cs
External/Plugins/CodeRefactor/Provider/CommandFactory.cs
External/Plugins/CodeRefactor/Provider/CommandFactoryProvider.cs
External/Plugins/CodeRefactor/Provider/ICommandFactory.cs

[CodeRefactor] Added validator for rename command.

---

External/Plugins/AS3Context/Context.cs

[AS3Context] Fixed autocomplete for 'var v:Vector.<T> = new Vector|'. fixes #1998. fixes #1947

---

Distros/HaxeDevelop/FlashDevelop/Bin/Debug/Docs/index.html
Distros/HaxeDevelop/FlashDevelop/Bin/Debug/StartPage/javascript/startpage.js
Distros/HaxeDevelop/FlashDevelop/Installer/Config.nsh
Distros/HaxeDevelop/PluginCore/PluginCore/DistroConfig.cs

Change the haxedevelop distro urls; https and no www

HaxeDevelop url changes
